#![allow(dead_code, mutable_transmutes, non_camel_case_types, non_snake_case, non_upper_case_globals, unused_assignments, unused_mut)]

use std::{time::Duration, thread::sleep};

use crate::SKP_Silk_NLSF_MSVQ_decode::{SKP_Silk_NLSF_CB_struct, SKP_Silk_NLSF_CBS};
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_10_CDF: [libc::c_ushort; 78] = [
    0 as libc::c_int as libc::c_ushort,
    17096 as libc::c_int as libc::c_ushort,
    24130 as libc::c_int as libc::c_ushort,
    28997 as libc::c_int as libc::c_ushort,
    33179 as libc::c_int as libc::c_ushort,
    36696 as libc::c_int as libc::c_ushort,
    40213 as libc::c_int as libc::c_ushort,
    42493 as libc::c_int as libc::c_ushort,
    44252 as libc::c_int as libc::c_ushort,
    45973 as libc::c_int as libc::c_ushort,
    47551 as libc::c_int as libc::c_ushort,
    49095 as libc::c_int as libc::c_ushort,
    50542 as libc::c_int as libc::c_ushort,
    51898 as libc::c_int as libc::c_ushort,
    53196 as libc::c_int as libc::c_ushort,
    54495 as libc::c_int as libc::c_ushort,
    55685 as libc::c_int as libc::c_ushort,
    56851 as libc::c_int as libc::c_ushort,
    57749 as libc::c_int as libc::c_ushort,
    58628 as libc::c_int as libc::c_ushort,
    59435 as libc::c_int as libc::c_ushort,
    60207 as libc::c_int as libc::c_ushort,
    60741 as libc::c_int as libc::c_ushort,
    61220 as libc::c_int as libc::c_ushort,
    61700 as libc::c_int as libc::c_ushort,
    62179 as libc::c_int as libc::c_ushort,
    62659 as libc::c_int as libc::c_ushort,
    63138 as libc::c_int as libc::c_ushort,
    63617 as libc::c_int as libc::c_ushort,
    64097 as libc::c_int as libc::c_ushort,
    64576 as libc::c_int as libc::c_ushort,
    65056 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    20378 as libc::c_int as libc::c_ushort,
    33032 as libc::c_int as libc::c_ushort,
    40395 as libc::c_int as libc::c_ushort,
    46721 as libc::c_int as libc::c_ushort,
    51707 as libc::c_int as libc::c_ushort,
    56585 as libc::c_int as libc::c_ushort,
    61157 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    15055 as libc::c_int as libc::c_ushort,
    25472 as libc::c_int as libc::c_ushort,
    35447 as libc::c_int as libc::c_ushort,
    42501 as libc::c_int as libc::c_ushort,
    48969 as libc::c_int as libc::c_ushort,
    54773 as libc::c_int as libc::c_ushort,
    60212 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    12069 as libc::c_int as libc::c_ushort,
    22440 as libc::c_int as libc::c_ushort,
    32812 as libc::c_int as libc::c_ushort,
    40145 as libc::c_int as libc::c_ushort,
    46870 as libc::c_int as libc::c_ushort,
    53595 as libc::c_int as libc::c_ushort,
    59630 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    10839 as libc::c_int as libc::c_ushort,
    19954 as libc::c_int as libc::c_ushort,
    27957 as libc::c_int as libc::c_ushort,
    35961 as libc::c_int as libc::c_ushort,
    43965 as libc::c_int as libc::c_ushort,
    51465 as libc::c_int as libc::c_ushort,
    58805 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    8933 as libc::c_int as libc::c_ushort,
    17674 as libc::c_int as libc::c_ushort,
    26415 as libc::c_int as libc::c_ushort,
    34785 as libc::c_int as libc::c_ushort,
    42977 as libc::c_int as libc::c_ushort,
    50820 as libc::c_int as libc::c_ushort,
    58496 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_10_CDF_start_ptr: [*const libc::c_ushort; 6] = [0
    as *const libc::c_ushort; 6];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_10_CDF_middle_idx: [libc::c_int; 6] = [
    5 as libc::c_int,
    3 as libc::c_int,
    4 as libc::c_int,
    4 as libc::c_int,
    5 as libc::c_int,
    5 as libc::c_int,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q5: [libc::c_short; 72] = [
    62 as libc::c_int as libc::c_short,
    103 as libc::c_int as libc::c_short,
    120 as libc::c_int as libc::c_short,
    127 as libc::c_int as libc::c_short,
    135 as libc::c_int as libc::c_short,
    135 as libc::c_int as libc::c_short,
    155 as libc::c_int as libc::c_short,
    167 as libc::c_int as libc::c_short,
    168 as libc::c_int as libc::c_short,
    172 as libc::c_int as libc::c_short,
    173 as libc::c_int as libc::c_short,
    176 as libc::c_int as libc::c_short,
    179 as libc::c_int as libc::c_short,
    181 as libc::c_int as libc::c_short,
    181 as libc::c_int as libc::c_short,
    185 as libc::c_int as libc::c_short,
    186 as libc::c_int as libc::c_short,
    198 as libc::c_int as libc::c_short,
    199 as libc::c_int as libc::c_short,
    203 as libc::c_int as libc::c_short,
    205 as libc::c_int as libc::c_short,
    222 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    54 as libc::c_int as libc::c_short,
    76 as libc::c_int as libc::c_short,
    101 as libc::c_int as libc::c_short,
    108 as libc::c_int as libc::c_short,
    119 as libc::c_int as libc::c_short,
    120 as libc::c_int as libc::c_short,
    123 as libc::c_int as libc::c_short,
    125 as libc::c_int as libc::c_short,
    68 as libc::c_int as libc::c_short,
    85 as libc::c_int as libc::c_short,
    87 as libc::c_int as libc::c_short,
    103 as libc::c_int as libc::c_short,
    107 as libc::c_int as libc::c_short,
    112 as libc::c_int as libc::c_short,
    115 as libc::c_int as libc::c_short,
    116 as libc::c_int as libc::c_short,
    78 as libc::c_int as libc::c_short,
    85 as libc::c_int as libc::c_short,
    85 as libc::c_int as libc::c_short,
    101 as libc::c_int as libc::c_short,
    105 as libc::c_int as libc::c_short,
    105 as libc::c_int as libc::c_short,
    110 as libc::c_int as libc::c_short,
    111 as libc::c_int as libc::c_short,
    83 as libc::c_int as libc::c_short,
    91 as libc::c_int as libc::c_short,
    97 as libc::c_int as libc::c_short,
    97 as libc::c_int as libc::c_short,
    97 as libc::c_int as libc::c_short,
    100 as libc::c_int as libc::c_short,
    101 as libc::c_int as libc::c_short,
    105 as libc::c_int as libc::c_short,
    92 as libc::c_int as libc::c_short,
    93 as libc::c_int as libc::c_short,
    93 as libc::c_int as libc::c_short,
    95 as libc::c_int as libc::c_short,
    96 as libc::c_int as libc::c_short,
    98 as libc::c_int as libc::c_short,
    99 as libc::c_int as libc::c_short,
    103 as libc::c_int as libc::c_short,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_10_ndelta_min_Q15: [libc::c_int; 11] = [
    462 as libc::c_int,
    3 as libc::c_int,
    64 as libc::c_int,
    74 as libc::c_int,
    98 as libc::c_int,
    50 as libc::c_int,
    97 as libc::c_int,
    68 as libc::c_int,
    120 as libc::c_int,
    53 as libc::c_int,
    639 as libc::c_int,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_10_Q15: [libc::c_short; 720] = [
    1877 as libc::c_int as libc::c_short,
    4646 as libc::c_int as libc::c_short,
    7712 as libc::c_int as libc::c_short,
    10745 as libc::c_int as libc::c_short,
    13964 as libc::c_int as libc::c_short,
    17028 as libc::c_int as libc::c_short,
    20239 as libc::c_int as libc::c_short,
    23182 as libc::c_int as libc::c_short,
    26471 as libc::c_int as libc::c_short,
    29287 as libc::c_int as libc::c_short,
    1612 as libc::c_int as libc::c_short,
    3278 as libc::c_int as libc::c_short,
    7086 as libc::c_int as libc::c_short,
    9975 as libc::c_int as libc::c_short,
    13228 as libc::c_int as libc::c_short,
    16264 as libc::c_int as libc::c_short,
    19596 as libc::c_int as libc::c_short,
    22690 as libc::c_int as libc::c_short,
    26037 as libc::c_int as libc::c_short,
    28965 as libc::c_int as libc::c_short,
    2169 as libc::c_int as libc::c_short,
    3830 as libc::c_int as libc::c_short,
    6460 as libc::c_int as libc::c_short,
    8958 as libc::c_int as libc::c_short,
    11960 as libc::c_int as libc::c_short,
    14750 as libc::c_int as libc::c_short,
    18408 as libc::c_int as libc::c_short,
    21659 as libc::c_int as libc::c_short,
    25018 as libc::c_int as libc::c_short,
    28043 as libc::c_int as libc::c_short,
    3680 as libc::c_int as libc::c_short,
    6024 as libc::c_int as libc::c_short,
    8986 as libc::c_int as libc::c_short,
    12256 as libc::c_int as libc::c_short,
    15201 as libc::c_int as libc::c_short,
    18188 as libc::c_int as libc::c_short,
    21741 as libc::c_int as libc::c_short,
    24460 as libc::c_int as libc::c_short,
    27484 as libc::c_int as libc::c_short,
    30059 as libc::c_int as libc::c_short,
    2584 as libc::c_int as libc::c_short,
    5187 as libc::c_int as libc::c_short,
    7799 as libc::c_int as libc::c_short,
    10902 as libc::c_int as libc::c_short,
    13179 as libc::c_int as libc::c_short,
    15765 as libc::c_int as libc::c_short,
    19017 as libc::c_int as libc::c_short,
    22431 as libc::c_int as libc::c_short,
    25891 as libc::c_int as libc::c_short,
    28698 as libc::c_int as libc::c_short,
    3731 as libc::c_int as libc::c_short,
    5751 as libc::c_int as libc::c_short,
    8650 as libc::c_int as libc::c_short,
    11742 as libc::c_int as libc::c_short,
    15090 as libc::c_int as libc::c_short,
    17407 as libc::c_int as libc::c_short,
    20391 as libc::c_int as libc::c_short,
    23421 as libc::c_int as libc::c_short,
    26228 as libc::c_int as libc::c_short,
    29247 as libc::c_int as libc::c_short,
    2107 as libc::c_int as libc::c_short,
    6323 as libc::c_int as libc::c_short,
    8915 as libc::c_int as libc::c_short,
    12226 as libc::c_int as libc::c_short,
    14775 as libc::c_int as libc::c_short,
    17791 as libc::c_int as libc::c_short,
    20664 as libc::c_int as libc::c_short,
    23679 as libc::c_int as libc::c_short,
    26829 as libc::c_int as libc::c_short,
    29353 as libc::c_int as libc::c_short,
    1677 as libc::c_int as libc::c_short,
    2870 as libc::c_int as libc::c_short,
    5386 as libc::c_int as libc::c_short,
    8077 as libc::c_int as libc::c_short,
    11817 as libc::c_int as libc::c_short,
    15176 as libc::c_int as libc::c_short,
    18657 as libc::c_int as libc::c_short,
    22006 as libc::c_int as libc::c_short,
    25513 as libc::c_int as libc::c_short,
    28689 as libc::c_int as libc::c_short,
    2111 as libc::c_int as libc::c_short,
    3625 as libc::c_int as libc::c_short,
    7027 as libc::c_int as libc::c_short,
    10588 as libc::c_int as libc::c_short,
    14059 as libc::c_int as libc::c_short,
    17193 as libc::c_int as libc::c_short,
    21137 as libc::c_int as libc::c_short,
    24260 as libc::c_int as libc::c_short,
    27577 as libc::c_int as libc::c_short,
    30036 as libc::c_int as libc::c_short,
    2428 as libc::c_int as libc::c_short,
    4010 as libc::c_int as libc::c_short,
    5765 as libc::c_int as libc::c_short,
    9376 as libc::c_int as libc::c_short,
    13805 as libc::c_int as libc::c_short,
    15821 as libc::c_int as libc::c_short,
    19444 as libc::c_int as libc::c_short,
    22389 as libc::c_int as libc::c_short,
    25295 as libc::c_int as libc::c_short,
    29310 as libc::c_int as libc::c_short,
    2256 as libc::c_int as libc::c_short,
    4628 as libc::c_int as libc::c_short,
    8377 as libc::c_int as libc::c_short,
    12441 as libc::c_int as libc::c_short,
    15283 as libc::c_int as libc::c_short,
    19462 as libc::c_int as libc::c_short,
    22257 as libc::c_int as libc::c_short,
    25551 as libc::c_int as libc::c_short,
    28432 as libc::c_int as libc::c_short,
    30304 as libc::c_int as libc::c_short,
    2352 as libc::c_int as libc::c_short,
    3675 as libc::c_int as libc::c_short,
    6129 as libc::c_int as libc::c_short,
    11868 as libc::c_int as libc::c_short,
    14551 as libc::c_int as libc::c_short,
    16655 as libc::c_int as libc::c_short,
    19624 as libc::c_int as libc::c_short,
    21883 as libc::c_int as libc::c_short,
    26526 as libc::c_int as libc::c_short,
    28849 as libc::c_int as libc::c_short,
    5243 as libc::c_int as libc::c_short,
    7248 as libc::c_int as libc::c_short,
    10558 as libc::c_int as libc::c_short,
    13269 as libc::c_int as libc::c_short,
    15651 as libc::c_int as libc::c_short,
    17919 as libc::c_int as libc::c_short,
    21141 as libc::c_int as libc::c_short,
    23827 as libc::c_int as libc::c_short,
    27102 as libc::c_int as libc::c_short,
    29519 as libc::c_int as libc::c_short,
    4422 as libc::c_int as libc::c_short,
    6725 as libc::c_int as libc::c_short,
    10449 as libc::c_int as libc::c_short,
    13273 as libc::c_int as libc::c_short,
    16124 as libc::c_int as libc::c_short,
    19921 as libc::c_int as libc::c_short,
    22826 as libc::c_int as libc::c_short,
    26061 as libc::c_int as libc::c_short,
    28763 as libc::c_int as libc::c_short,
    30583 as libc::c_int as libc::c_short,
    4508 as libc::c_int as libc::c_short,
    6291 as libc::c_int as libc::c_short,
    9504 as libc::c_int as libc::c_short,
    11809 as libc::c_int as libc::c_short,
    13827 as libc::c_int as libc::c_short,
    15950 as libc::c_int as libc::c_short,
    19077 as libc::c_int as libc::c_short,
    22084 as libc::c_int as libc::c_short,
    25740 as libc::c_int as libc::c_short,
    28658 as libc::c_int as libc::c_short,
    2540 as libc::c_int as libc::c_short,
    4297 as libc::c_int as libc::c_short,
    8579 as libc::c_int as libc::c_short,
    13578 as libc::c_int as libc::c_short,
    16634 as libc::c_int as libc::c_short,
    19101 as libc::c_int as libc::c_short,
    21547 as libc::c_int as libc::c_short,
    23887 as libc::c_int as libc::c_short,
    26777 as libc::c_int as libc::c_short,
    29146 as libc::c_int as libc::c_short,
    3377 as libc::c_int as libc::c_short,
    6358 as libc::c_int as libc::c_short,
    10224 as libc::c_int as libc::c_short,
    14518 as libc::c_int as libc::c_short,
    17905 as libc::c_int as libc::c_short,
    21056 as libc::c_int as libc::c_short,
    23637 as libc::c_int as libc::c_short,
    25784 as libc::c_int as libc::c_short,
    28161 as libc::c_int as libc::c_short,
    30109 as libc::c_int as libc::c_short,
    4177 as libc::c_int as libc::c_short,
    5942 as libc::c_int as libc::c_short,
    8159 as libc::c_int as libc::c_short,
    10108 as libc::c_int as libc::c_short,
    12130 as libc::c_int as libc::c_short,
    15470 as libc::c_int as libc::c_short,
    20191 as libc::c_int as libc::c_short,
    23326 as libc::c_int as libc::c_short,
    26782 as libc::c_int as libc::c_short,
    29359 as libc::c_int as libc::c_short,
    2492 as libc::c_int as libc::c_short,
    3801 as libc::c_int as libc::c_short,
    6144 as libc::c_int as libc::c_short,
    9825 as libc::c_int as libc::c_short,
    16000 as libc::c_int as libc::c_short,
    18671 as libc::c_int as libc::c_short,
    20893 as libc::c_int as libc::c_short,
    23663 as libc::c_int as libc::c_short,
    25899 as libc::c_int as libc::c_short,
    28974 as libc::c_int as libc::c_short,
    3011 as libc::c_int as libc::c_short,
    4727 as libc::c_int as libc::c_short,
    6834 as libc::c_int as libc::c_short,
    10505 as libc::c_int as libc::c_short,
    12465 as libc::c_int as libc::c_short,
    14496 as libc::c_int as libc::c_short,
    17065 as libc::c_int as libc::c_short,
    20052 as libc::c_int as libc::c_short,
    25265 as libc::c_int as libc::c_short,
    28057 as libc::c_int as libc::c_short,
    4149 as libc::c_int as libc::c_short,
    7197 as libc::c_int as libc::c_short,
    12338 as libc::c_int as libc::c_short,
    15076 as libc::c_int as libc::c_short,
    18002 as libc::c_int as libc::c_short,
    20190 as libc::c_int as libc::c_short,
    22187 as libc::c_int as libc::c_short,
    24723 as libc::c_int as libc::c_short,
    27083 as libc::c_int as libc::c_short,
    29125 as libc::c_int as libc::c_short,
    2975 as libc::c_int as libc::c_short,
    4578 as libc::c_int as libc::c_short,
    6448 as libc::c_int as libc::c_short,
    8378 as libc::c_int as libc::c_short,
    9671 as libc::c_int as libc::c_short,
    13225 as libc::c_int as libc::c_short,
    19502 as libc::c_int as libc::c_short,
    22277 as libc::c_int as libc::c_short,
    26058 as libc::c_int as libc::c_short,
    28850 as libc::c_int as libc::c_short,
    4102 as libc::c_int as libc::c_short,
    5760 as libc::c_int as libc::c_short,
    7744 as libc::c_int as libc::c_short,
    9484 as libc::c_int as libc::c_short,
    10744 as libc::c_int as libc::c_short,
    12308 as libc::c_int as libc::c_short,
    14677 as libc::c_int as libc::c_short,
    19607 as libc::c_int as libc::c_short,
    24841 as libc::c_int as libc::c_short,
    28381 as libc::c_int as libc::c_short,
    4931 as libc::c_int as libc::c_short,
    9287 as libc::c_int as libc::c_short,
    12477 as libc::c_int as libc::c_short,
    13395 as libc::c_int as libc::c_short,
    13712 as libc::c_int as libc::c_short,
    14351 as libc::c_int as libc::c_short,
    16048 as libc::c_int as libc::c_short,
    19867 as libc::c_int as libc::c_short,
    24188 as libc::c_int as libc::c_short,
    28994 as libc::c_int as libc::c_short,
    4141 as libc::c_int as libc::c_short,
    7867 as libc::c_int as libc::c_short,
    13140 as libc::c_int as libc::c_short,
    17720 as libc::c_int as libc::c_short,
    20064 as libc::c_int as libc::c_short,
    21108 as libc::c_int as libc::c_short,
    21692 as libc::c_int as libc::c_short,
    22722 as libc::c_int as libc::c_short,
    23736 as libc::c_int as libc::c_short,
    27449 as libc::c_int as libc::c_short,
    4011 as libc::c_int as libc::c_short,
    8720 as libc::c_int as libc::c_short,
    13234 as libc::c_int as libc::c_short,
    16206 as libc::c_int as libc::c_short,
    17601 as libc::c_int as libc::c_short,
    18289 as libc::c_int as libc::c_short,
    18524 as libc::c_int as libc::c_short,
    19689 as libc::c_int as libc::c_short,
    23234 as libc::c_int as libc::c_short,
    27882 as libc::c_int as libc::c_short,
    3420 as libc::c_int as libc::c_short,
    5995 as libc::c_int as libc::c_short,
    11230 as libc::c_int as libc::c_short,
    15117 as libc::c_int as libc::c_short,
    15907 as libc::c_int as libc::c_short,
    16783 as libc::c_int as libc::c_short,
    17762 as libc::c_int as libc::c_short,
    23347 as libc::c_int as libc::c_short,
    26898 as libc::c_int as libc::c_short,
    29946 as libc::c_int as libc::c_short,
    3080 as libc::c_int as libc::c_short,
    6786 as libc::c_int as libc::c_short,
    10465 as libc::c_int as libc::c_short,
    13676 as libc::c_int as libc::c_short,
    18059 as libc::c_int as libc::c_short,
    23615 as libc::c_int as libc::c_short,
    27058 as libc::c_int as libc::c_short,
    29082 as libc::c_int as libc::c_short,
    29563 as libc::c_int as libc::c_short,
    29905 as libc::c_int as libc::c_short,
    3038 as libc::c_int as libc::c_short,
    5620 as libc::c_int as libc::c_short,
    9266 as libc::c_int as libc::c_short,
    12870 as libc::c_int as libc::c_short,
    18803 as libc::c_int as libc::c_short,
    19610 as libc::c_int as libc::c_short,
    20010 as libc::c_int as libc::c_short,
    20802 as libc::c_int as libc::c_short,
    23882 as libc::c_int as libc::c_short,
    29306 as libc::c_int as libc::c_short,
    3314 as libc::c_int as libc::c_short,
    6420 as libc::c_int as libc::c_short,
    9046 as libc::c_int as libc::c_short,
    13262 as libc::c_int as libc::c_short,
    15869 as libc::c_int as libc::c_short,
    23117 as libc::c_int as libc::c_short,
    23667 as libc::c_int as libc::c_short,
    24215 as libc::c_int as libc::c_short,
    24487 as libc::c_int as libc::c_short,
    25915 as libc::c_int as libc::c_short,
    3469 as libc::c_int as libc::c_short,
    6963 as libc::c_int as libc::c_short,
    10103 as libc::c_int as libc::c_short,
    15282 as libc::c_int as libc::c_short,
    20531 as libc::c_int as libc::c_short,
    23240 as libc::c_int as libc::c_short,
    25024 as libc::c_int as libc::c_short,
    26021 as libc::c_int as libc::c_short,
    26736 as libc::c_int as libc::c_short,
    27255 as libc::c_int as libc::c_short,
    3041 as libc::c_int as libc::c_short,
    6459 as libc::c_int as libc::c_short,
    9777 as libc::c_int as libc::c_short,
    12896 as libc::c_int as libc::c_short,
    16315 as libc::c_int as libc::c_short,
    19410 as libc::c_int as libc::c_short,
    24070 as libc::c_int as libc::c_short,
    29353 as libc::c_int as libc::c_short,
    31795 as libc::c_int as libc::c_short,
    32075 as libc::c_int as libc::c_short,
    -(200 as libc::c_int) as libc::c_short,
    -(134 as libc::c_int) as libc::c_short,
    -(113 as libc::c_int) as libc::c_short,
    -(204 as libc::c_int) as libc::c_short,
    -(347 as libc::c_int) as libc::c_short,
    -(440 as libc::c_int) as libc::c_short,
    -(352 as libc::c_int) as libc::c_short,
    -(211 as libc::c_int) as libc::c_short,
    -(418 as libc::c_int) as libc::c_short,
    -(172 as libc::c_int) as libc::c_short,
    -(313 as libc::c_int) as libc::c_short,
    59 as libc::c_int as libc::c_short,
    495 as libc::c_int as libc::c_short,
    772 as libc::c_int as libc::c_short,
    721 as libc::c_int as libc::c_short,
    614 as libc::c_int as libc::c_short,
    334 as libc::c_int as libc::c_short,
    444 as libc::c_int as libc::c_short,
    225 as libc::c_int as libc::c_short,
    242 as libc::c_int as libc::c_short,
    161 as libc::c_int as libc::c_short,
    16 as libc::c_int as libc::c_short,
    274 as libc::c_int as libc::c_short,
    564 as libc::c_int as libc::c_short,
    -(73 as libc::c_int) as libc::c_short,
    -(188 as libc::c_int) as libc::c_short,
    -(395 as libc::c_int) as libc::c_short,
    -(171 as libc::c_int) as libc::c_short,
    777 as libc::c_int as libc::c_short,
    508 as libc::c_int as libc::c_short,
    1340 as libc::c_int as libc::c_short,
    1145 as libc::c_int as libc::c_short,
    699 as libc::c_int as libc::c_short,
    196 as libc::c_int as libc::c_short,
    223 as libc::c_int as libc::c_short,
    173 as libc::c_int as libc::c_short,
    90 as libc::c_int as libc::c_short,
    25 as libc::c_int as libc::c_short,
    -(26 as libc::c_int) as libc::c_short,
    18 as libc::c_int as libc::c_short,
    133 as libc::c_int as libc::c_short,
    -(105 as libc::c_int) as libc::c_short,
    -(360 as libc::c_int) as libc::c_short,
    -(277 as libc::c_int) as libc::c_short,
    859 as libc::c_int as libc::c_short,
    634 as libc::c_int as libc::c_short,
    41 as libc::c_int as libc::c_short,
    -(557 as libc::c_int) as libc::c_short,
    -(768 as libc::c_int) as libc::c_short,
    -(926 as libc::c_int) as libc::c_short,
    -(601 as libc::c_int) as libc::c_short,
    -(1021 as libc::c_int) as libc::c_short,
    -(1189 as libc::c_int) as libc::c_short,
    -(365 as libc::c_int) as libc::c_short,
    225 as libc::c_int as libc::c_short,
    107 as libc::c_int as libc::c_short,
    374 as libc::c_int as libc::c_short,
    -(50 as libc::c_int) as libc::c_short,
    433 as libc::c_int as libc::c_short,
    417 as libc::c_int as libc::c_short,
    156 as libc::c_int as libc::c_short,
    39 as libc::c_int as libc::c_short,
    -(597 as libc::c_int) as libc::c_short,
    -(1397 as libc::c_int) as libc::c_short,
    -(1594 as libc::c_int) as libc::c_short,
    -(592 as libc::c_int) as libc::c_short,
    -(485 as libc::c_int) as libc::c_short,
    -(292 as libc::c_int) as libc::c_short,
    253 as libc::c_int as libc::c_short,
    87 as libc::c_int as libc::c_short,
    -(0 as libc::c_int) as libc::c_short,
    -(6 as libc::c_int) as libc::c_short,
    -(25 as libc::c_int) as libc::c_short,
    -(345 as libc::c_int) as libc::c_short,
    -(240 as libc::c_int) as libc::c_short,
    120 as libc::c_int as libc::c_short,
    1261 as libc::c_int as libc::c_short,
    946 as libc::c_int as libc::c_short,
    166 as libc::c_int as libc::c_short,
    -(277 as libc::c_int) as libc::c_short,
    241 as libc::c_int as libc::c_short,
    167 as libc::c_int as libc::c_short,
    170 as libc::c_int as libc::c_short,
    429 as libc::c_int as libc::c_short,
    518 as libc::c_int as libc::c_short,
    714 as libc::c_int as libc::c_short,
    602 as libc::c_int as libc::c_short,
    254 as libc::c_int as libc::c_short,
    134 as libc::c_int as libc::c_short,
    92 as libc::c_int as libc::c_short,
    -(152 as libc::c_int) as libc::c_short,
    -(324 as libc::c_int) as libc::c_short,
    -(394 as libc::c_int) as libc::c_short,
    49 as libc::c_int as libc::c_short,
    -(151 as libc::c_int) as libc::c_short,
    -(304 as libc::c_int) as libc::c_short,
    -(724 as libc::c_int) as libc::c_short,
    -(657 as libc::c_int) as libc::c_short,
    -(162 as libc::c_int) as libc::c_short,
    -(369 as libc::c_int) as libc::c_short,
    -(35 as libc::c_int) as libc::c_short,
    3 as libc::c_int as libc::c_short,
    -(2 as libc::c_int) as libc::c_short,
    -(312 as libc::c_int) as libc::c_short,
    -(200 as libc::c_int) as libc::c_short,
    -(92 as libc::c_int) as libc::c_short,
    -(227 as libc::c_int) as libc::c_short,
    242 as libc::c_int as libc::c_short,
    628 as libc::c_int as libc::c_short,
    565 as libc::c_int as libc::c_short,
    -(124 as libc::c_int) as libc::c_short,
    1056 as libc::c_int as libc::c_short,
    770 as libc::c_int as libc::c_short,
    101 as libc::c_int as libc::c_short,
    -(84 as libc::c_int) as libc::c_short,
    -(33 as libc::c_int) as libc::c_short,
    4 as libc::c_int as libc::c_short,
    -(192 as libc::c_int) as libc::c_short,
    -(272 as libc::c_int) as libc::c_short,
    5 as libc::c_int as libc::c_short,
    -(627 as libc::c_int) as libc::c_short,
    -(977 as libc::c_int) as libc::c_short,
    419 as libc::c_int as libc::c_short,
    472 as libc::c_int as libc::c_short,
    53 as libc::c_int as libc::c_short,
    -(103 as libc::c_int) as libc::c_short,
    145 as libc::c_int as libc::c_short,
    322 as libc::c_int as libc::c_short,
    -(95 as libc::c_int) as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    -(100 as libc::c_int) as libc::c_short,
    -(303 as libc::c_int) as libc::c_short,
    -(560 as libc::c_int) as libc::c_short,
    -(1067 as libc::c_int) as libc::c_short,
    -(413 as libc::c_int) as libc::c_short,
    714 as libc::c_int as libc::c_short,
    283 as libc::c_int as libc::c_short,
    2 as libc::c_int as libc::c_short,
    -(223 as libc::c_int) as libc::c_short,
    -(367 as libc::c_int) as libc::c_short,
    523 as libc::c_int as libc::c_short,
    360 as libc::c_int as libc::c_short,
    -(38 as libc::c_int) as libc::c_short,
    -(115 as libc::c_int) as libc::c_short,
    378 as libc::c_int as libc::c_short,
    -(591 as libc::c_int) as libc::c_short,
    -(718 as libc::c_int) as libc::c_short,
    448 as libc::c_int as libc::c_short,
    -(481 as libc::c_int) as libc::c_short,
    -(274 as libc::c_int) as libc::c_short,
    180 as libc::c_int as libc::c_short,
    -(88 as libc::c_int) as libc::c_short,
    -(581 as libc::c_int) as libc::c_short,
    -(157 as libc::c_int) as libc::c_short,
    -(696 as libc::c_int) as libc::c_short,
    -(1265 as libc::c_int) as libc::c_short,
    394 as libc::c_int as libc::c_short,
    -(479 as libc::c_int) as libc::c_short,
    -(23 as libc::c_int) as libc::c_short,
    124 as libc::c_int as libc::c_short,
    -(43 as libc::c_int) as libc::c_short,
    19 as libc::c_int as libc::c_short,
    -(113 as libc::c_int) as libc::c_short,
    -(236 as libc::c_int) as libc::c_short,
    -(412 as libc::c_int) as libc::c_short,
    -(659 as libc::c_int) as libc::c_short,
    -(200 as libc::c_int) as libc::c_short,
    2 as libc::c_int as libc::c_short,
    -(69 as libc::c_int) as libc::c_short,
    -(342 as libc::c_int) as libc::c_short,
    199 as libc::c_int as libc::c_short,
    55 as libc::c_int as libc::c_short,
    58 as libc::c_int as libc::c_short,
    -(36 as libc::c_int) as libc::c_short,
    -(51 as libc::c_int) as libc::c_short,
    -(62 as libc::c_int) as libc::c_short,
    507 as libc::c_int as libc::c_short,
    507 as libc::c_int as libc::c_short,
    427 as libc::c_int as libc::c_short,
    442 as libc::c_int as libc::c_short,
    36 as libc::c_int as libc::c_short,
    601 as libc::c_int as libc::c_short,
    -(141 as libc::c_int) as libc::c_short,
    68 as libc::c_int as libc::c_short,
    274 as libc::c_int as libc::c_short,
    274 as libc::c_int as libc::c_short,
    68 as libc::c_int as libc::c_short,
    -(12 as libc::c_int) as libc::c_short,
    -(4 as libc::c_int) as libc::c_short,
    71 as libc::c_int as libc::c_short,
    -(193 as libc::c_int) as libc::c_short,
    -(464 as libc::c_int) as libc::c_short,
    -(425 as libc::c_int) as libc::c_short,
    -(383 as libc::c_int) as libc::c_short,
    408 as libc::c_int as libc::c_short,
    203 as libc::c_int as libc::c_short,
    -(337 as libc::c_int) as libc::c_short,
    236 as libc::c_int as libc::c_short,
    410 as libc::c_int as libc::c_short,
    -(59 as libc::c_int) as libc::c_short,
    -(25 as libc::c_int) as libc::c_short,
    -(341 as libc::c_int) as libc::c_short,
    -(449 as libc::c_int) as libc::c_short,
    28 as libc::c_int as libc::c_short,
    -(9 as libc::c_int) as libc::c_short,
    90 as libc::c_int as libc::c_short,
    332 as libc::c_int as libc::c_short,
    -(14 as libc::c_int) as libc::c_short,
    -(905 as libc::c_int) as libc::c_short,
    96 as libc::c_int as libc::c_short,
    -(540 as libc::c_int) as libc::c_short,
    -(242 as libc::c_int) as libc::c_short,
    679 as libc::c_int as libc::c_short,
    -(59 as libc::c_int) as libc::c_short,
    192 as libc::c_int as libc::c_short,
    -(24 as libc::c_int) as libc::c_short,
    60 as libc::c_int as libc::c_short,
    -(217 as libc::c_int) as libc::c_short,
    5 as libc::c_int as libc::c_short,
    -(37 as libc::c_int) as libc::c_short,
    179 as libc::c_int as libc::c_short,
    -(20 as libc::c_int) as libc::c_short,
    311 as libc::c_int as libc::c_short,
    519 as libc::c_int as libc::c_short,
    274 as libc::c_int as libc::c_short,
    72 as libc::c_int as libc::c_short,
    -(326 as libc::c_int) as libc::c_short,
    -(1030 as libc::c_int) as libc::c_short,
    -(262 as libc::c_int) as libc::c_short,
    213 as libc::c_int as libc::c_short,
    380 as libc::c_int as libc::c_short,
    82 as libc::c_int as libc::c_short,
    328 as libc::c_int as libc::c_short,
    411 as libc::c_int as libc::c_short,
    -(540 as libc::c_int) as libc::c_short,
    574 as libc::c_int as libc::c_short,
    -(283 as libc::c_int) as libc::c_short,
    151 as libc::c_int as libc::c_short,
    181 as libc::c_int as libc::c_short,
    -(402 as libc::c_int) as libc::c_short,
    -(278 as libc::c_int) as libc::c_short,
    -(240 as libc::c_int) as libc::c_short,
    -(110 as libc::c_int) as libc::c_short,
    -(227 as libc::c_int) as libc::c_short,
    -(264 as libc::c_int) as libc::c_short,
    -(89 as libc::c_int) as libc::c_short,
    -(250 as libc::c_int) as libc::c_short,
    -(259 as libc::c_int) as libc::c_short,
    -(27 as libc::c_int) as libc::c_short,
    106 as libc::c_int as libc::c_short,
    -(239 as libc::c_int) as libc::c_short,
    -(98 as libc::c_int) as libc::c_short,
    -(390 as libc::c_int) as libc::c_short,
    118 as libc::c_int as libc::c_short,
    61 as libc::c_int as libc::c_short,
    104 as libc::c_int as libc::c_short,
    294 as libc::c_int as libc::c_short,
    532 as libc::c_int as libc::c_short,
    92 as libc::c_int as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    60 as libc::c_int as libc::c_short,
    -(233 as libc::c_int) as libc::c_short,
    335 as libc::c_int as libc::c_short,
    541 as libc::c_int as libc::c_short,
    307 as libc::c_int as libc::c_short,
    -(26 as libc::c_int) as libc::c_short,
    -(110 as libc::c_int) as libc::c_short,
    -(91 as libc::c_int) as libc::c_short,
    -(231 as libc::c_int) as libc::c_short,
    -(460 as libc::c_int) as libc::c_short,
    170 as libc::c_int as libc::c_short,
    201 as libc::c_int as libc::c_short,
    96 as libc::c_int as libc::c_short,
    -(372 as libc::c_int) as libc::c_short,
    132 as libc::c_int as libc::c_short,
    435 as libc::c_int as libc::c_short,
    -(302 as libc::c_int) as libc::c_short,
    216 as libc::c_int as libc::c_short,
    -(279 as libc::c_int) as libc::c_short,
    -(41 as libc::c_int) as libc::c_short,
    74 as libc::c_int as libc::c_short,
    190 as libc::c_int as libc::c_short,
    368 as libc::c_int as libc::c_short,
    273 as libc::c_int as libc::c_short,
    -(186 as libc::c_int) as libc::c_short,
    -(608 as libc::c_int) as libc::c_short,
    -(157 as libc::c_int) as libc::c_short,
    159 as libc::c_int as libc::c_short,
    12 as libc::c_int as libc::c_short,
    278 as libc::c_int as libc::c_short,
    245 as libc::c_int as libc::c_short,
    307 as libc::c_int as libc::c_short,
    25 as libc::c_int as libc::c_short,
    -(187 as libc::c_int) as libc::c_short,
    -(16 as libc::c_int) as libc::c_short,
    55 as libc::c_int as libc::c_short,
    30 as libc::c_int as libc::c_short,
    -(163 as libc::c_int) as libc::c_short,
    548 as libc::c_int as libc::c_short,
    -(307 as libc::c_int) as libc::c_short,
    106 as libc::c_int as libc::c_short,
    -(5 as libc::c_int) as libc::c_short,
    27 as libc::c_int as libc::c_short,
    330 as libc::c_int as libc::c_short,
    -(416 as libc::c_int) as libc::c_short,
    475 as libc::c_int as libc::c_short,
    438 as libc::c_int as libc::c_short,
    -(235 as libc::c_int) as libc::c_short,
    104 as libc::c_int as libc::c_short,
    137 as libc::c_int as libc::c_short,
    21 as libc::c_int as libc::c_short,
    -(5 as libc::c_int) as libc::c_short,
    -(300 as libc::c_int) as libc::c_short,
    -(468 as libc::c_int) as libc::c_short,
    521 as libc::c_int as libc::c_short,
    -(347 as libc::c_int) as libc::c_short,
    170 as libc::c_int as libc::c_short,
    -(200 as libc::c_int) as libc::c_short,
    -(219 as libc::c_int) as libc::c_short,
    308 as libc::c_int as libc::c_short,
    -(122 as libc::c_int) as libc::c_short,
    -(133 as libc::c_int) as libc::c_short,
    219 as libc::c_int as libc::c_short,
    -(16 as libc::c_int) as libc::c_short,
    359 as libc::c_int as libc::c_short,
    412 as libc::c_int as libc::c_short,
    -(89 as libc::c_int) as libc::c_short,
    -(111 as libc::c_int) as libc::c_short,
    48 as libc::c_int as libc::c_short,
    322 as libc::c_int as libc::c_short,
    142 as libc::c_int as libc::c_short,
    177 as libc::c_int as libc::c_short,
    -(286 as libc::c_int) as libc::c_short,
    -(127 as libc::c_int) as libc::c_short,
    -(39 as libc::c_int) as libc::c_short,
    -(63 as libc::c_int) as libc::c_short,
    -(42 as libc::c_int) as libc::c_short,
    -(451 as libc::c_int) as libc::c_short,
    160 as libc::c_int as libc::c_short,
    308 as libc::c_int as libc::c_short,
    -(57 as libc::c_int) as libc::c_short,
    193 as libc::c_int as libc::c_short,
    -(48 as libc::c_int) as libc::c_short,
    74 as libc::c_int as libc::c_short,
    -(346 as libc::c_int) as libc::c_short,
    59 as libc::c_int as libc::c_short,
    -(27 as libc::c_int) as libc::c_short,
    27 as libc::c_int as libc::c_short,
    -(469 as libc::c_int) as libc::c_short,
    -(277 as libc::c_int) as libc::c_short,
    -(344 as libc::c_int) as libc::c_short,
    282 as libc::c_int as libc::c_short,
    262 as libc::c_int as libc::c_short,
    122 as libc::c_int as libc::c_short,
    171 as libc::c_int as libc::c_short,
    -(249 as libc::c_int) as libc::c_short,
    27 as libc::c_int as libc::c_short,
    258 as libc::c_int as libc::c_short,
    188 as libc::c_int as libc::c_short,
    -(3 as libc::c_int) as libc::c_short,
    67 as libc::c_int as libc::c_short,
    -(206 as libc::c_int) as libc::c_short,
    -(284 as libc::c_int) as libc::c_short,
    291 as libc::c_int as libc::c_short,
    -(117 as libc::c_int) as libc::c_short,
    -(88 as libc::c_int) as libc::c_short,
    -(477 as libc::c_int) as libc::c_short,
    375 as libc::c_int as libc::c_short,
    50 as libc::c_int as libc::c_short,
    106 as libc::c_int as libc::c_short,
    99 as libc::c_int as libc::c_short,
    -(182 as libc::c_int) as libc::c_short,
    438 as libc::c_int as libc::c_short,
    -(376 as libc::c_int) as libc::c_short,
    -(401 as libc::c_int) as libc::c_short,
    -(49 as libc::c_int) as libc::c_short,
    119 as libc::c_int as libc::c_short,
    -(23 as libc::c_int) as libc::c_short,
    -(10 as libc::c_int) as libc::c_short,
    -(48 as libc::c_int) as libc::c_short,
    -(116 as libc::c_int) as libc::c_short,
    -(200 as libc::c_int) as libc::c_short,
    -(310 as libc::c_int) as libc::c_short,
    121 as libc::c_int as libc::c_short,
    73 as libc::c_int as libc::c_short,
    7 as libc::c_int as libc::c_short,
    237 as libc::c_int as libc::c_short,
    -(226 as libc::c_int) as libc::c_short,
    139 as libc::c_int as libc::c_short,
    -(456 as libc::c_int) as libc::c_short,
    397 as libc::c_int as libc::c_short,
    35 as libc::c_int as libc::c_short,
    3 as libc::c_int as libc::c_short,
    -(108 as libc::c_int) as libc::c_short,
    323 as libc::c_int as libc::c_short,
    -(75 as libc::c_int) as libc::c_short,
    332 as libc::c_int as libc::c_short,
    198 as libc::c_int as libc::c_short,
    -(99 as libc::c_int) as libc::c_short,
    -(21 as libc::c_int) as libc::c_short,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_CB1_10_Stage_info: [SKP_Silk_NLSF_CBS; 6] = [SKP_Silk_NLSF_CBS {
    nVectors: 0,
    CB_NLSF_Q15: 0 as *const libc::c_short,
    Rates_Q5: 0 as *const libc::c_short,
}; 6];
#[no_mangle]
pub static mut SKP_Silk_NLSF_CB1_10: SKP_Silk_NLSF_CB_struct = unsafe {
    {
        let mut init = SKP_Silk_NLSF_CB_struct {
            nStages: 6 as libc::c_int,
            CBStages: SKP_Silk_NLSF_CB1_10_Stage_info.as_ptr(),
            NDeltaMin_Q15: SKP_Silk_NLSF_MSVQ_CB1_10_ndelta_min_Q15.as_ptr(),
            CDF: SKP_Silk_NLSF_MSVQ_CB1_10_CDF.as_ptr(),
            StartPtr: SKP_Silk_NLSF_MSVQ_CB1_10_CDF_start_ptr.as_ptr(),
            MiddleIx: SKP_Silk_NLSF_MSVQ_CB1_10_CDF_middle_idx.as_ptr(),
        };
        init
    }
};
unsafe extern "C" fn run_static_initializers() {
    SKP_Silk_NLSF_MSVQ_CB1_10_CDF_start_ptr = [
        &*SKP_Silk_NLSF_MSVQ_CB1_10_CDF.as_ptr().offset(0 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_10_CDF.as_ptr().offset(33 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_10_CDF.as_ptr().offset(42 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_10_CDF.as_ptr().offset(51 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_10_CDF.as_ptr().offset(60 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_10_CDF.as_ptr().offset(69 as libc::c_int as isize)
            as *const libc::c_ushort,
    ];
    SKP_Silk_NLSF_CB1_10_Stage_info = [
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 32 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_10_Q15
                    .as_ptr()
                    .offset((10 as libc::c_int * 0 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q5
                    .as_ptr()
                    .offset(0 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_10_Q15
                    .as_ptr()
                    .offset((10 as libc::c_int * 32 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q5
                    .as_ptr()
                    .offset(32 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_10_Q15
                    .as_ptr()
                    .offset((10 as libc::c_int * 40 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q5
                    .as_ptr()
                    .offset(40 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_10_Q15
                    .as_ptr()
                    .offset((10 as libc::c_int * 48 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q5
                    .as_ptr()
                    .offset(48 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_10_Q15
                    .as_ptr()
                    .offset((10 as libc::c_int * 56 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q5
                    .as_ptr()
                    .offset(56 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_10_Q15
                    .as_ptr()
                    .offset((10 as libc::c_int * 64 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q5
                    .as_ptr()
                    .offset(64 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
    ];
    sleep(Duration::from_nanos(1));
}
#[used]
#[cfg_attr(target_os = "linux", link_section = ".init_array")]
#[cfg_attr(target_os = "windows", link_section = ".CRT$XIB")]
#[cfg_attr(target_os = "macos", link_section = "__DATA,__mod_init_func")]
static INIT_ARRAY: [unsafe extern "C" fn(); 1] = [run_static_initializers];
