#![allow(dead_code, mutable_transmutes, non_camel_case_types, non_snake_case, non_upper_case_globals, unused_assignments, unused_mut)]

use std::{thread::sleep, time::Duration};
use crate::SKP_Silk_NLSF_MSVQ_decode::{SKP_Silk_NLSF_CB_struct, SKP_Silk_NLSF_CBS};
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_16_CDF: [libc::c_ushort; 114] = [
    0 as libc::c_int as libc::c_ushort,
    19099 as libc::c_int as libc::c_ushort,
    26957 as libc::c_int as libc::c_ushort,
    30639 as libc::c_int as libc::c_ushort,
    34242 as libc::c_int as libc::c_ushort,
    37546 as libc::c_int as libc::c_ushort,
    40447 as libc::c_int as libc::c_ushort,
    43287 as libc::c_int as libc::c_ushort,
    46005 as libc::c_int as libc::c_ushort,
    48445 as libc::c_int as libc::c_ushort,
    49865 as libc::c_int as libc::c_ushort,
    51284 as libc::c_int as libc::c_ushort,
    52673 as libc::c_int as libc::c_ushort,
    53975 as libc::c_int as libc::c_ushort,
    55221 as libc::c_int as libc::c_ushort,
    56441 as libc::c_int as libc::c_ushort,
    57267 as libc::c_int as libc::c_ushort,
    58025 as libc::c_int as libc::c_ushort,
    58648 as libc::c_int as libc::c_ushort,
    59232 as libc::c_int as libc::c_ushort,
    59768 as libc::c_int as libc::c_ushort,
    60248 as libc::c_int as libc::c_ushort,
    60729 as libc::c_int as libc::c_ushort,
    61210 as libc::c_int as libc::c_ushort,
    61690 as libc::c_int as libc::c_ushort,
    62171 as libc::c_int as libc::c_ushort,
    62651 as libc::c_int as libc::c_ushort,
    63132 as libc::c_int as libc::c_ushort,
    63613 as libc::c_int as libc::c_ushort,
    64093 as libc::c_int as libc::c_ushort,
    64574 as libc::c_int as libc::c_ushort,
    65054 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    28808 as libc::c_int as libc::c_ushort,
    38775 as libc::c_int as libc::c_ushort,
    46801 as libc::c_int as libc::c_ushort,
    51785 as libc::c_int as libc::c_ushort,
    55886 as libc::c_int as libc::c_ushort,
    59410 as libc::c_int as libc::c_ushort,
    62572 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    27376 as libc::c_int as libc::c_ushort,
    38639 as libc::c_int as libc::c_ushort,
    45052 as libc::c_int as libc::c_ushort,
    51465 as libc::c_int as libc::c_ushort,
    55448 as libc::c_int as libc::c_ushort,
    59021 as libc::c_int as libc::c_ushort,
    62594 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    33403 as libc::c_int as libc::c_ushort,
    39569 as libc::c_int as libc::c_ushort,
    45102 as libc::c_int as libc::c_ushort,
    49961 as libc::c_int as libc::c_ushort,
    54047 as libc::c_int as libc::c_ushort,
    57959 as libc::c_int as libc::c_ushort,
    61788 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    25851 as libc::c_int as libc::c_ushort,
    43356 as libc::c_int as libc::c_ushort,
    47828 as libc::c_int as libc::c_ushort,
    52204 as libc::c_int as libc::c_ushort,
    55964 as libc::c_int as libc::c_ushort,
    59413 as libc::c_int as libc::c_ushort,
    62507 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    34277 as libc::c_int as libc::c_ushort,
    40337 as libc::c_int as libc::c_ushort,
    45432 as libc::c_int as libc::c_ushort,
    50311 as libc::c_int as libc::c_ushort,
    54326 as libc::c_int as libc::c_ushort,
    58171 as libc::c_int as libc::c_ushort,
    61853 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    33538 as libc::c_int as libc::c_ushort,
    39865 as libc::c_int as libc::c_ushort,
    45302 as libc::c_int as libc::c_ushort,
    50076 as libc::c_int as libc::c_ushort,
    54549 as libc::c_int as libc::c_ushort,
    58478 as libc::c_int as libc::c_ushort,
    62159 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    27445 as libc::c_int as libc::c_ushort,
    35258 as libc::c_int as libc::c_ushort,
    40665 as libc::c_int as libc::c_ushort,
    46072 as libc::c_int as libc::c_ushort,
    51362 as libc::c_int as libc::c_ushort,
    56540 as libc::c_int as libc::c_ushort,
    61086 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    22080 as libc::c_int as libc::c_ushort,
    30779 as libc::c_int as libc::c_ushort,
    37065 as libc::c_int as libc::c_ushort,
    43085 as libc::c_int as libc::c_ushort,
    48849 as libc::c_int as libc::c_ushort,
    54613 as libc::c_int as libc::c_ushort,
    60133 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    13417 as libc::c_int as libc::c_ushort,
    21748 as libc::c_int as libc::c_ushort,
    30078 as libc::c_int as libc::c_ushort,
    38231 as libc::c_int as libc::c_ushort,
    46383 as libc::c_int as libc::c_ushort,
    53091 as libc::c_int as libc::c_ushort,
    59515 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_16_CDF_start_ptr: [*const libc::c_ushort; 10] = [0
    as *const libc::c_ushort; 10];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_16_CDF_middle_idx: [libc::c_int; 10] = [
    5 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    3 as libc::c_int,
    3 as libc::c_int,
    4 as libc::c_int,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5: [libc::c_short; 104] = [
    57 as libc::c_int as libc::c_short,
    98 as libc::c_int as libc::c_short,
    133 as libc::c_int as libc::c_short,
    134 as libc::c_int as libc::c_short,
    138 as libc::c_int as libc::c_short,
    144 as libc::c_int as libc::c_short,
    145 as libc::c_int as libc::c_short,
    147 as libc::c_int as libc::c_short,
    152 as libc::c_int as libc::c_short,
    177 as libc::c_int as libc::c_short,
    177 as libc::c_int as libc::c_short,
    178 as libc::c_int as libc::c_short,
    181 as libc::c_int as libc::c_short,
    183 as libc::c_int as libc::c_short,
    184 as libc::c_int as libc::c_short,
    202 as libc::c_int as libc::c_short,
    206 as libc::c_int as libc::c_short,
    215 as libc::c_int as libc::c_short,
    218 as libc::c_int as libc::c_short,
    222 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    227 as libc::c_int as libc::c_short,
    38 as libc::c_int as libc::c_short,
    87 as libc::c_int as libc::c_short,
    97 as libc::c_int as libc::c_short,
    119 as libc::c_int as libc::c_short,
    128 as libc::c_int as libc::c_short,
    135 as libc::c_int as libc::c_short,
    140 as libc::c_int as libc::c_short,
    143 as libc::c_int as libc::c_short,
    40 as libc::c_int as libc::c_short,
    81 as libc::c_int as libc::c_short,
    107 as libc::c_int as libc::c_short,
    107 as libc::c_int as libc::c_short,
    129 as libc::c_int as libc::c_short,
    134 as libc::c_int as libc::c_short,
    134 as libc::c_int as libc::c_short,
    143 as libc::c_int as libc::c_short,
    31 as libc::c_int as libc::c_short,
    109 as libc::c_int as libc::c_short,
    114 as libc::c_int as libc::c_short,
    120 as libc::c_int as libc::c_short,
    128 as libc::c_int as libc::c_short,
    130 as libc::c_int as libc::c_short,
    131 as libc::c_int as libc::c_short,
    132 as libc::c_int as libc::c_short,
    43 as libc::c_int as libc::c_short,
    61 as libc::c_int as libc::c_short,
    124 as libc::c_int as libc::c_short,
    125 as libc::c_int as libc::c_short,
    132 as libc::c_int as libc::c_short,
    136 as libc::c_int as libc::c_short,
    141 as libc::c_int as libc::c_short,
    142 as libc::c_int as libc::c_short,
    30 as libc::c_int as libc::c_short,
    110 as libc::c_int as libc::c_short,
    118 as libc::c_int as libc::c_short,
    120 as libc::c_int as libc::c_short,
    129 as libc::c_int as libc::c_short,
    131 as libc::c_int as libc::c_short,
    133 as libc::c_int as libc::c_short,
    133 as libc::c_int as libc::c_short,
    31 as libc::c_int as libc::c_short,
    108 as libc::c_int as libc::c_short,
    115 as libc::c_int as libc::c_short,
    121 as libc::c_int as libc::c_short,
    124 as libc::c_int as libc::c_short,
    130 as libc::c_int as libc::c_short,
    133 as libc::c_int as libc::c_short,
    137 as libc::c_int as libc::c_short,
    40 as libc::c_int as libc::c_short,
    98 as libc::c_int as libc::c_short,
    115 as libc::c_int as libc::c_short,
    115 as libc::c_int as libc::c_short,
    116 as libc::c_int as libc::c_short,
    117 as libc::c_int as libc::c_short,
    123 as libc::c_int as libc::c_short,
    124 as libc::c_int as libc::c_short,
    50 as libc::c_int as libc::c_short,
    93 as libc::c_int as libc::c_short,
    108 as libc::c_int as libc::c_short,
    110 as libc::c_int as libc::c_short,
    112 as libc::c_int as libc::c_short,
    112 as libc::c_int as libc::c_short,
    114 as libc::c_int as libc::c_short,
    115 as libc::c_int as libc::c_short,
    73 as libc::c_int as libc::c_short,
    95 as libc::c_int as libc::c_short,
    95 as libc::c_int as libc::c_short,
    96 as libc::c_int as libc::c_short,
    96 as libc::c_int as libc::c_short,
    105 as libc::c_int as libc::c_short,
    107 as libc::c_int as libc::c_short,
    110 as libc::c_int as libc::c_short,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_16_ndelta_min_Q15: [libc::c_int; 17] = [
    148 as libc::c_int,
    3 as libc::c_int,
    60 as libc::c_int,
    68 as libc::c_int,
    117 as libc::c_int,
    86 as libc::c_int,
    121 as libc::c_int,
    124 as libc::c_int,
    152 as libc::c_int,
    153 as libc::c_int,
    207 as libc::c_int,
    151 as libc::c_int,
    225 as libc::c_int,
    239 as libc::c_int,
    126 as libc::c_int,
    183 as libc::c_int,
    792 as libc::c_int,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_MSVQ_CB1_16_Q15: [libc::c_short; 1664] = [
    1309 as libc::c_int as libc::c_short,
    3060 as libc::c_int as libc::c_short,
    5071 as libc::c_int as libc::c_short,
    6996 as libc::c_int as libc::c_short,
    9028 as libc::c_int as libc::c_short,
    10938 as libc::c_int as libc::c_short,
    12934 as libc::c_int as libc::c_short,
    14891 as libc::c_int as libc::c_short,
    16933 as libc::c_int as libc::c_short,
    18854 as libc::c_int as libc::c_short,
    20792 as libc::c_int as libc::c_short,
    22764 as libc::c_int as libc::c_short,
    24753 as libc::c_int as libc::c_short,
    26659 as libc::c_int as libc::c_short,
    28626 as libc::c_int as libc::c_short,
    30501 as libc::c_int as libc::c_short,
    1264 as libc::c_int as libc::c_short,
    2745 as libc::c_int as libc::c_short,
    4610 as libc::c_int as libc::c_short,
    6408 as libc::c_int as libc::c_short,
    8286 as libc::c_int as libc::c_short,
    10043 as libc::c_int as libc::c_short,
    12084 as libc::c_int as libc::c_short,
    14108 as libc::c_int as libc::c_short,
    16118 as libc::c_int as libc::c_short,
    18163 as libc::c_int as libc::c_short,
    20095 as libc::c_int as libc::c_short,
    22164 as libc::c_int as libc::c_short,
    24264 as libc::c_int as libc::c_short,
    26316 as libc::c_int as libc::c_short,
    28329 as libc::c_int as libc::c_short,
    30251 as libc::c_int as libc::c_short,
    1044 as libc::c_int as libc::c_short,
    2080 as libc::c_int as libc::c_short,
    3672 as libc::c_int as libc::c_short,
    5179 as libc::c_int as libc::c_short,
    7140 as libc::c_int as libc::c_short,
    9100 as libc::c_int as libc::c_short,
    11070 as libc::c_int as libc::c_short,
    13065 as libc::c_int as libc::c_short,
    15423 as libc::c_int as libc::c_short,
    17790 as libc::c_int as libc::c_short,
    19931 as libc::c_int as libc::c_short,
    22101 as libc::c_int as libc::c_short,
    24290 as libc::c_int as libc::c_short,
    26361 as libc::c_int as libc::c_short,
    28499 as libc::c_int as libc::c_short,
    30418 as libc::c_int as libc::c_short,
    1131 as libc::c_int as libc::c_short,
    2476 as libc::c_int as libc::c_short,
    4478 as libc::c_int as libc::c_short,
    6149 as libc::c_int as libc::c_short,
    7902 as libc::c_int as libc::c_short,
    9875 as libc::c_int as libc::c_short,
    11938 as libc::c_int as libc::c_short,
    13809 as libc::c_int as libc::c_short,
    15869 as libc::c_int as libc::c_short,
    17730 as libc::c_int as libc::c_short,
    19948 as libc::c_int as libc::c_short,
    21707 as libc::c_int as libc::c_short,
    23761 as libc::c_int as libc::c_short,
    25535 as libc::c_int as libc::c_short,
    27426 as libc::c_int as libc::c_short,
    28917 as libc::c_int as libc::c_short,
    1040 as libc::c_int as libc::c_short,
    2004 as libc::c_int as libc::c_short,
    4026 as libc::c_int as libc::c_short,
    6100 as libc::c_int as libc::c_short,
    8432 as libc::c_int as libc::c_short,
    10494 as libc::c_int as libc::c_short,
    12610 as libc::c_int as libc::c_short,
    14694 as libc::c_int as libc::c_short,
    16797 as libc::c_int as libc::c_short,
    18775 as libc::c_int as libc::c_short,
    20799 as libc::c_int as libc::c_short,
    22782 as libc::c_int as libc::c_short,
    24772 as libc::c_int as libc::c_short,
    26682 as libc::c_int as libc::c_short,
    28631 as libc::c_int as libc::c_short,
    30516 as libc::c_int as libc::c_short,
    2310 as libc::c_int as libc::c_short,
    3812 as libc::c_int as libc::c_short,
    5913 as libc::c_int as libc::c_short,
    7933 as libc::c_int as libc::c_short,
    10033 as libc::c_int as libc::c_short,
    11881 as libc::c_int as libc::c_short,
    13885 as libc::c_int as libc::c_short,
    15798 as libc::c_int as libc::c_short,
    17751 as libc::c_int as libc::c_short,
    19576 as libc::c_int as libc::c_short,
    21482 as libc::c_int as libc::c_short,
    23276 as libc::c_int as libc::c_short,
    25157 as libc::c_int as libc::c_short,
    27010 as libc::c_int as libc::c_short,
    28833 as libc::c_int as libc::c_short,
    30623 as libc::c_int as libc::c_short,
    1254 as libc::c_int as libc::c_short,
    2847 as libc::c_int as libc::c_short,
    5013 as libc::c_int as libc::c_short,
    6781 as libc::c_int as libc::c_short,
    8626 as libc::c_int as libc::c_short,
    10370 as libc::c_int as libc::c_short,
    12726 as libc::c_int as libc::c_short,
    14633 as libc::c_int as libc::c_short,
    16281 as libc::c_int as libc::c_short,
    17852 as libc::c_int as libc::c_short,
    19870 as libc::c_int as libc::c_short,
    21472 as libc::c_int as libc::c_short,
    23002 as libc::c_int as libc::c_short,
    24629 as libc::c_int as libc::c_short,
    26710 as libc::c_int as libc::c_short,
    27960 as libc::c_int as libc::c_short,
    1468 as libc::c_int as libc::c_short,
    3059 as libc::c_int as libc::c_short,
    4987 as libc::c_int as libc::c_short,
    7026 as libc::c_int as libc::c_short,
    8741 as libc::c_int as libc::c_short,
    10412 as libc::c_int as libc::c_short,
    12281 as libc::c_int as libc::c_short,
    14020 as libc::c_int as libc::c_short,
    15970 as libc::c_int as libc::c_short,
    17723 as libc::c_int as libc::c_short,
    19640 as libc::c_int as libc::c_short,
    21522 as libc::c_int as libc::c_short,
    23472 as libc::c_int as libc::c_short,
    25661 as libc::c_int as libc::c_short,
    27986 as libc::c_int as libc::c_short,
    30225 as libc::c_int as libc::c_short,
    2171 as libc::c_int as libc::c_short,
    3566 as libc::c_int as libc::c_short,
    5605 as libc::c_int as libc::c_short,
    7384 as libc::c_int as libc::c_short,
    9404 as libc::c_int as libc::c_short,
    11220 as libc::c_int as libc::c_short,
    13030 as libc::c_int as libc::c_short,
    14758 as libc::c_int as libc::c_short,
    16687 as libc::c_int as libc::c_short,
    18417 as libc::c_int as libc::c_short,
    20346 as libc::c_int as libc::c_short,
    22091 as libc::c_int as libc::c_short,
    24055 as libc::c_int as libc::c_short,
    26212 as libc::c_int as libc::c_short,
    28356 as libc::c_int as libc::c_short,
    30397 as libc::c_int as libc::c_short,
    2409 as libc::c_int as libc::c_short,
    4676 as libc::c_int as libc::c_short,
    7543 as libc::c_int as libc::c_short,
    9786 as libc::c_int as libc::c_short,
    11419 as libc::c_int as libc::c_short,
    12935 as libc::c_int as libc::c_short,
    14368 as libc::c_int as libc::c_short,
    15653 as libc::c_int as libc::c_short,
    17366 as libc::c_int as libc::c_short,
    18943 as libc::c_int as libc::c_short,
    20762 as libc::c_int as libc::c_short,
    22477 as libc::c_int as libc::c_short,
    24440 as libc::c_int as libc::c_short,
    26327 as libc::c_int as libc::c_short,
    28284 as libc::c_int as libc::c_short,
    30242 as libc::c_int as libc::c_short,
    2354 as libc::c_int as libc::c_short,
    4222 as libc::c_int as libc::c_short,
    6820 as libc::c_int as libc::c_short,
    9107 as libc::c_int as libc::c_short,
    11596 as libc::c_int as libc::c_short,
    13934 as libc::c_int as libc::c_short,
    15973 as libc::c_int as libc::c_short,
    17682 as libc::c_int as libc::c_short,
    19158 as libc::c_int as libc::c_short,
    20517 as libc::c_int as libc::c_short,
    21991 as libc::c_int as libc::c_short,
    23420 as libc::c_int as libc::c_short,
    25178 as libc::c_int as libc::c_short,
    26936 as libc::c_int as libc::c_short,
    28794 as libc::c_int as libc::c_short,
    30527 as libc::c_int as libc::c_short,
    1323 as libc::c_int as libc::c_short,
    2414 as libc::c_int as libc::c_short,
    4184 as libc::c_int as libc::c_short,
    6039 as libc::c_int as libc::c_short,
    7534 as libc::c_int as libc::c_short,
    9398 as libc::c_int as libc::c_short,
    11099 as libc::c_int as libc::c_short,
    13097 as libc::c_int as libc::c_short,
    14799 as libc::c_int as libc::c_short,
    16451 as libc::c_int as libc::c_short,
    18434 as libc::c_int as libc::c_short,
    20887 as libc::c_int as libc::c_short,
    23490 as libc::c_int as libc::c_short,
    25838 as libc::c_int as libc::c_short,
    28046 as libc::c_int as libc::c_short,
    30225 as libc::c_int as libc::c_short,
    1361 as libc::c_int as libc::c_short,
    3243 as libc::c_int as libc::c_short,
    6048 as libc::c_int as libc::c_short,
    8511 as libc::c_int as libc::c_short,
    11001 as libc::c_int as libc::c_short,
    13145 as libc::c_int as libc::c_short,
    15073 as libc::c_int as libc::c_short,
    16608 as libc::c_int as libc::c_short,
    18126 as libc::c_int as libc::c_short,
    19381 as libc::c_int as libc::c_short,
    20912 as libc::c_int as libc::c_short,
    22607 as libc::c_int as libc::c_short,
    24660 as libc::c_int as libc::c_short,
    26668 as libc::c_int as libc::c_short,
    28663 as libc::c_int as libc::c_short,
    30566 as libc::c_int as libc::c_short,
    1216 as libc::c_int as libc::c_short,
    2648 as libc::c_int as libc::c_short,
    5901 as libc::c_int as libc::c_short,
    8422 as libc::c_int as libc::c_short,
    10037 as libc::c_int as libc::c_short,
    11425 as libc::c_int as libc::c_short,
    12973 as libc::c_int as libc::c_short,
    14603 as libc::c_int as libc::c_short,
    16686 as libc::c_int as libc::c_short,
    18600 as libc::c_int as libc::c_short,
    20555 as libc::c_int as libc::c_short,
    22415 as libc::c_int as libc::c_short,
    24450 as libc::c_int as libc::c_short,
    26280 as libc::c_int as libc::c_short,
    28206 as libc::c_int as libc::c_short,
    30077 as libc::c_int as libc::c_short,
    2417 as libc::c_int as libc::c_short,
    4048 as libc::c_int as libc::c_short,
    6316 as libc::c_int as libc::c_short,
    8433 as libc::c_int as libc::c_short,
    10510 as libc::c_int as libc::c_short,
    12757 as libc::c_int as libc::c_short,
    15072 as libc::c_int as libc::c_short,
    17295 as libc::c_int as libc::c_short,
    19573 as libc::c_int as libc::c_short,
    21503 as libc::c_int as libc::c_short,
    23329 as libc::c_int as libc::c_short,
    24782 as libc::c_int as libc::c_short,
    26235 as libc::c_int as libc::c_short,
    27689 as libc::c_int as libc::c_short,
    29214 as libc::c_int as libc::c_short,
    30819 as libc::c_int as libc::c_short,
    1012 as libc::c_int as libc::c_short,
    2345 as libc::c_int as libc::c_short,
    4991 as libc::c_int as libc::c_short,
    7377 as libc::c_int as libc::c_short,
    9465 as libc::c_int as libc::c_short,
    11916 as libc::c_int as libc::c_short,
    14296 as libc::c_int as libc::c_short,
    16566 as libc::c_int as libc::c_short,
    18672 as libc::c_int as libc::c_short,
    20544 as libc::c_int as libc::c_short,
    22292 as libc::c_int as libc::c_short,
    23838 as libc::c_int as libc::c_short,
    25415 as libc::c_int as libc::c_short,
    27050 as libc::c_int as libc::c_short,
    28848 as libc::c_int as libc::c_short,
    30551 as libc::c_int as libc::c_short,
    1937 as libc::c_int as libc::c_short,
    3693 as libc::c_int as libc::c_short,
    6267 as libc::c_int as libc::c_short,
    8019 as libc::c_int as libc::c_short,
    10372 as libc::c_int as libc::c_short,
    12194 as libc::c_int as libc::c_short,
    14287 as libc::c_int as libc::c_short,
    15657 as libc::c_int as libc::c_short,
    17431 as libc::c_int as libc::c_short,
    18864 as libc::c_int as libc::c_short,
    20769 as libc::c_int as libc::c_short,
    22206 as libc::c_int as libc::c_short,
    24037 as libc::c_int as libc::c_short,
    25463 as libc::c_int as libc::c_short,
    27383 as libc::c_int as libc::c_short,
    28602 as libc::c_int as libc::c_short,
    1969 as libc::c_int as libc::c_short,
    3305 as libc::c_int as libc::c_short,
    5017 as libc::c_int as libc::c_short,
    6726 as libc::c_int as libc::c_short,
    8375 as libc::c_int as libc::c_short,
    9993 as libc::c_int as libc::c_short,
    11634 as libc::c_int as libc::c_short,
    13280 as libc::c_int as libc::c_short,
    15078 as libc::c_int as libc::c_short,
    16751 as libc::c_int as libc::c_short,
    18464 as libc::c_int as libc::c_short,
    20119 as libc::c_int as libc::c_short,
    21959 as libc::c_int as libc::c_short,
    23858 as libc::c_int as libc::c_short,
    26224 as libc::c_int as libc::c_short,
    29298 as libc::c_int as libc::c_short,
    1198 as libc::c_int as libc::c_short,
    2647 as libc::c_int as libc::c_short,
    5428 as libc::c_int as libc::c_short,
    7423 as libc::c_int as libc::c_short,
    9775 as libc::c_int as libc::c_short,
    12155 as libc::c_int as libc::c_short,
    14665 as libc::c_int as libc::c_short,
    16344 as libc::c_int as libc::c_short,
    18121 as libc::c_int as libc::c_short,
    19790 as libc::c_int as libc::c_short,
    21557 as libc::c_int as libc::c_short,
    22847 as libc::c_int as libc::c_short,
    24484 as libc::c_int as libc::c_short,
    25742 as libc::c_int as libc::c_short,
    27639 as libc::c_int as libc::c_short,
    28711 as libc::c_int as libc::c_short,
    1636 as libc::c_int as libc::c_short,
    3353 as libc::c_int as libc::c_short,
    5447 as libc::c_int as libc::c_short,
    7597 as libc::c_int as libc::c_short,
    9837 as libc::c_int as libc::c_short,
    11647 as libc::c_int as libc::c_short,
    13964 as libc::c_int as libc::c_short,
    16019 as libc::c_int as libc::c_short,
    17862 as libc::c_int as libc::c_short,
    20116 as libc::c_int as libc::c_short,
    22319 as libc::c_int as libc::c_short,
    24037 as libc::c_int as libc::c_short,
    25966 as libc::c_int as libc::c_short,
    28086 as libc::c_int as libc::c_short,
    29914 as libc::c_int as libc::c_short,
    31294 as libc::c_int as libc::c_short,
    2676 as libc::c_int as libc::c_short,
    4105 as libc::c_int as libc::c_short,
    6378 as libc::c_int as libc::c_short,
    8223 as libc::c_int as libc::c_short,
    10058 as libc::c_int as libc::c_short,
    11549 as libc::c_int as libc::c_short,
    13072 as libc::c_int as libc::c_short,
    14453 as libc::c_int as libc::c_short,
    15956 as libc::c_int as libc::c_short,
    17355 as libc::c_int as libc::c_short,
    18931 as libc::c_int as libc::c_short,
    20402 as libc::c_int as libc::c_short,
    22183 as libc::c_int as libc::c_short,
    23884 as libc::c_int as libc::c_short,
    25717 as libc::c_int as libc::c_short,
    27723 as libc::c_int as libc::c_short,
    1373 as libc::c_int as libc::c_short,
    2593 as libc::c_int as libc::c_short,
    4449 as libc::c_int as libc::c_short,
    5633 as libc::c_int as libc::c_short,
    7300 as libc::c_int as libc::c_short,
    8425 as libc::c_int as libc::c_short,
    9474 as libc::c_int as libc::c_short,
    10818 as libc::c_int as libc::c_short,
    12769 as libc::c_int as libc::c_short,
    15722 as libc::c_int as libc::c_short,
    19002 as libc::c_int as libc::c_short,
    21429 as libc::c_int as libc::c_short,
    23682 as libc::c_int as libc::c_short,
    25924 as libc::c_int as libc::c_short,
    28135 as libc::c_int as libc::c_short,
    30333 as libc::c_int as libc::c_short,
    1596 as libc::c_int as libc::c_short,
    3183 as libc::c_int as libc::c_short,
    5378 as libc::c_int as libc::c_short,
    7164 as libc::c_int as libc::c_short,
    8670 as libc::c_int as libc::c_short,
    10105 as libc::c_int as libc::c_short,
    11470 as libc::c_int as libc::c_short,
    12834 as libc::c_int as libc::c_short,
    13991 as libc::c_int as libc::c_short,
    15042 as libc::c_int as libc::c_short,
    16642 as libc::c_int as libc::c_short,
    17903 as libc::c_int as libc::c_short,
    20759 as libc::c_int as libc::c_short,
    25283 as libc::c_int as libc::c_short,
    27770 as libc::c_int as libc::c_short,
    30240 as libc::c_int as libc::c_short,
    2037 as libc::c_int as libc::c_short,
    3987 as libc::c_int as libc::c_short,
    6237 as libc::c_int as libc::c_short,
    8117 as libc::c_int as libc::c_short,
    9954 as libc::c_int as libc::c_short,
    12245 as libc::c_int as libc::c_short,
    14217 as libc::c_int as libc::c_short,
    15892 as libc::c_int as libc::c_short,
    17775 as libc::c_int as libc::c_short,
    20114 as libc::c_int as libc::c_short,
    22314 as libc::c_int as libc::c_short,
    25942 as libc::c_int as libc::c_short,
    26305 as libc::c_int as libc::c_short,
    26483 as libc::c_int as libc::c_short,
    26796 as libc::c_int as libc::c_short,
    28561 as libc::c_int as libc::c_short,
    2181 as libc::c_int as libc::c_short,
    3858 as libc::c_int as libc::c_short,
    5760 as libc::c_int as libc::c_short,
    7924 as libc::c_int as libc::c_short,
    10041 as libc::c_int as libc::c_short,
    11577 as libc::c_int as libc::c_short,
    13769 as libc::c_int as libc::c_short,
    15700 as libc::c_int as libc::c_short,
    17429 as libc::c_int as libc::c_short,
    19879 as libc::c_int as libc::c_short,
    23583 as libc::c_int as libc::c_short,
    24538 as libc::c_int as libc::c_short,
    25212 as libc::c_int as libc::c_short,
    25693 as libc::c_int as libc::c_short,
    28688 as libc::c_int as libc::c_short,
    30507 as libc::c_int as libc::c_short,
    1992 as libc::c_int as libc::c_short,
    3882 as libc::c_int as libc::c_short,
    6474 as libc::c_int as libc::c_short,
    7883 as libc::c_int as libc::c_short,
    9381 as libc::c_int as libc::c_short,
    12672 as libc::c_int as libc::c_short,
    14340 as libc::c_int as libc::c_short,
    15701 as libc::c_int as libc::c_short,
    16658 as libc::c_int as libc::c_short,
    17832 as libc::c_int as libc::c_short,
    20850 as libc::c_int as libc::c_short,
    22885 as libc::c_int as libc::c_short,
    24677 as libc::c_int as libc::c_short,
    26457 as libc::c_int as libc::c_short,
    28491 as libc::c_int as libc::c_short,
    30460 as libc::c_int as libc::c_short,
    2391 as libc::c_int as libc::c_short,
    3988 as libc::c_int as libc::c_short,
    5448 as libc::c_int as libc::c_short,
    7432 as libc::c_int as libc::c_short,
    11014 as libc::c_int as libc::c_short,
    12579 as libc::c_int as libc::c_short,
    13140 as libc::c_int as libc::c_short,
    14146 as libc::c_int as libc::c_short,
    15898 as libc::c_int as libc::c_short,
    18592 as libc::c_int as libc::c_short,
    21104 as libc::c_int as libc::c_short,
    22993 as libc::c_int as libc::c_short,
    24673 as libc::c_int as libc::c_short,
    27186 as libc::c_int as libc::c_short,
    28142 as libc::c_int as libc::c_short,
    29612 as libc::c_int as libc::c_short,
    1713 as libc::c_int as libc::c_short,
    5102 as libc::c_int as libc::c_short,
    6989 as libc::c_int as libc::c_short,
    7798 as libc::c_int as libc::c_short,
    8670 as libc::c_int as libc::c_short,
    10110 as libc::c_int as libc::c_short,
    12746 as libc::c_int as libc::c_short,
    14881 as libc::c_int as libc::c_short,
    16709 as libc::c_int as libc::c_short,
    18407 as libc::c_int as libc::c_short,
    20126 as libc::c_int as libc::c_short,
    22107 as libc::c_int as libc::c_short,
    24181 as libc::c_int as libc::c_short,
    26198 as libc::c_int as libc::c_short,
    28237 as libc::c_int as libc::c_short,
    30137 as libc::c_int as libc::c_short,
    1612 as libc::c_int as libc::c_short,
    3617 as libc::c_int as libc::c_short,
    6148 as libc::c_int as libc::c_short,
    8359 as libc::c_int as libc::c_short,
    9576 as libc::c_int as libc::c_short,
    11528 as libc::c_int as libc::c_short,
    14936 as libc::c_int as libc::c_short,
    17809 as libc::c_int as libc::c_short,
    18287 as libc::c_int as libc::c_short,
    18729 as libc::c_int as libc::c_short,
    19001 as libc::c_int as libc::c_short,
    21111 as libc::c_int as libc::c_short,
    24631 as libc::c_int as libc::c_short,
    26596 as libc::c_int as libc::c_short,
    28740 as libc::c_int as libc::c_short,
    30643 as libc::c_int as libc::c_short,
    2266 as libc::c_int as libc::c_short,
    4168 as libc::c_int as libc::c_short,
    7862 as libc::c_int as libc::c_short,
    9546 as libc::c_int as libc::c_short,
    9618 as libc::c_int as libc::c_short,
    9703 as libc::c_int as libc::c_short,
    10134 as libc::c_int as libc::c_short,
    13897 as libc::c_int as libc::c_short,
    16265 as libc::c_int as libc::c_short,
    18432 as libc::c_int as libc::c_short,
    20587 as libc::c_int as libc::c_short,
    22605 as libc::c_int as libc::c_short,
    24754 as libc::c_int as libc::c_short,
    26994 as libc::c_int as libc::c_short,
    29125 as libc::c_int as libc::c_short,
    30840 as libc::c_int as libc::c_short,
    1840 as libc::c_int as libc::c_short,
    3917 as libc::c_int as libc::c_short,
    6272 as libc::c_int as libc::c_short,
    7809 as libc::c_int as libc::c_short,
    9714 as libc::c_int as libc::c_short,
    11438 as libc::c_int as libc::c_short,
    13767 as libc::c_int as libc::c_short,
    15799 as libc::c_int as libc::c_short,
    19244 as libc::c_int as libc::c_short,
    21972 as libc::c_int as libc::c_short,
    22980 as libc::c_int as libc::c_short,
    23180 as libc::c_int as libc::c_short,
    23723 as libc::c_int as libc::c_short,
    25650 as libc::c_int as libc::c_short,
    29117 as libc::c_int as libc::c_short,
    31085 as libc::c_int as libc::c_short,
    1458 as libc::c_int as libc::c_short,
    3612 as libc::c_int as libc::c_short,
    6008 as libc::c_int as libc::c_short,
    7488 as libc::c_int as libc::c_short,
    9827 as libc::c_int as libc::c_short,
    11893 as libc::c_int as libc::c_short,
    14086 as libc::c_int as libc::c_short,
    15734 as libc::c_int as libc::c_short,
    17440 as libc::c_int as libc::c_short,
    19535 as libc::c_int as libc::c_short,
    22424 as libc::c_int as libc::c_short,
    24767 as libc::c_int as libc::c_short,
    29246 as libc::c_int as libc::c_short,
    29928 as libc::c_int as libc::c_short,
    30516 as libc::c_int as libc::c_short,
    30947 as libc::c_int as libc::c_short,
    -(102 as libc::c_int) as libc::c_short,
    -(121 as libc::c_int) as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    -(6 as libc::c_int) as libc::c_short,
    5 as libc::c_int as libc::c_short,
    -(2 as libc::c_int) as libc::c_short,
    8 as libc::c_int as libc::c_short,
    -(18 as libc::c_int) as libc::c_short,
    -(4 as libc::c_int) as libc::c_short,
    6 as libc::c_int as libc::c_short,
    14 as libc::c_int as libc::c_short,
    -(2 as libc::c_int) as libc::c_short,
    -(12 as libc::c_int) as libc::c_short,
    -(16 as libc::c_int) as libc::c_short,
    -(12 as libc::c_int) as libc::c_short,
    -(60 as libc::c_int) as libc::c_short,
    -(126 as libc::c_int) as libc::c_short,
    -(353 as libc::c_int) as libc::c_short,
    -(574 as libc::c_int) as libc::c_short,
    -(677 as libc::c_int) as libc::c_short,
    -(657 as libc::c_int) as libc::c_short,
    -(617 as libc::c_int) as libc::c_short,
    -(498 as libc::c_int) as libc::c_short,
    -(393 as libc::c_int) as libc::c_short,
    -(348 as libc::c_int) as libc::c_short,
    -(277 as libc::c_int) as libc::c_short,
    -(225 as libc::c_int) as libc::c_short,
    -(164 as libc::c_int) as libc::c_short,
    -(102 as libc::c_int) as libc::c_short,
    -(70 as libc::c_int) as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    33 as libc::c_int as libc::c_short,
    4 as libc::c_int as libc::c_short,
    379 as libc::c_int as libc::c_short,
    387 as libc::c_int as libc::c_short,
    551 as libc::c_int as libc::c_short,
    605 as libc::c_int as libc::c_short,
    620 as libc::c_int as libc::c_short,
    532 as libc::c_int as libc::c_short,
    482 as libc::c_int as libc::c_short,
    442 as libc::c_int as libc::c_short,
    454 as libc::c_int as libc::c_short,
    385 as libc::c_int as libc::c_short,
    347 as libc::c_int as libc::c_short,
    322 as libc::c_int as libc::c_short,
    299 as libc::c_int as libc::c_short,
    266 as libc::c_int as libc::c_short,
    200 as libc::c_int as libc::c_short,
    1168 as libc::c_int as libc::c_short,
    951 as libc::c_int as libc::c_short,
    672 as libc::c_int as libc::c_short,
    246 as libc::c_int as libc::c_short,
    60 as libc::c_int as libc::c_short,
    -(161 as libc::c_int) as libc::c_short,
    -(259 as libc::c_int) as libc::c_short,
    -(234 as libc::c_int) as libc::c_short,
    -(253 as libc::c_int) as libc::c_short,
    -(282 as libc::c_int) as libc::c_short,
    -(203 as libc::c_int) as libc::c_short,
    -(187 as libc::c_int) as libc::c_short,
    -(155 as libc::c_int) as libc::c_short,
    -(176 as libc::c_int) as libc::c_short,
    -(198 as libc::c_int) as libc::c_short,
    -(178 as libc::c_int) as libc::c_short,
    10 as libc::c_int as libc::c_short,
    170 as libc::c_int as libc::c_short,
    393 as libc::c_int as libc::c_short,
    609 as libc::c_int as libc::c_short,
    555 as libc::c_int as libc::c_short,
    208 as libc::c_int as libc::c_short,
    -(330 as libc::c_int) as libc::c_short,
    -(571 as libc::c_int) as libc::c_short,
    -(769 as libc::c_int) as libc::c_short,
    -(633 as libc::c_int) as libc::c_short,
    -(319 as libc::c_int) as libc::c_short,
    -(43 as libc::c_int) as libc::c_short,
    95 as libc::c_int as libc::c_short,
    105 as libc::c_int as libc::c_short,
    106 as libc::c_int as libc::c_short,
    116 as libc::c_int as libc::c_short,
    -(152 as libc::c_int) as libc::c_short,
    -(140 as libc::c_int) as libc::c_short,
    -(125 as libc::c_int) as libc::c_short,
    5 as libc::c_int as libc::c_short,
    173 as libc::c_int as libc::c_short,
    274 as libc::c_int as libc::c_short,
    264 as libc::c_int as libc::c_short,
    331 as libc::c_int as libc::c_short,
    -(37 as libc::c_int) as libc::c_short,
    -(293 as libc::c_int) as libc::c_short,
    -(609 as libc::c_int) as libc::c_short,
    -(786 as libc::c_int) as libc::c_short,
    -(959 as libc::c_int) as libc::c_short,
    -(814 as libc::c_int) as libc::c_short,
    -(645 as libc::c_int) as libc::c_short,
    -(238 as libc::c_int) as libc::c_short,
    -(91 as libc::c_int) as libc::c_short,
    36 as libc::c_int as libc::c_short,
    -(11 as libc::c_int) as libc::c_short,
    -(101 as libc::c_int) as libc::c_short,
    -(279 as libc::c_int) as libc::c_short,
    -(227 as libc::c_int) as libc::c_short,
    -(40 as libc::c_int) as libc::c_short,
    90 as libc::c_int as libc::c_short,
    530 as libc::c_int as libc::c_short,
    677 as libc::c_int as libc::c_short,
    890 as libc::c_int as libc::c_short,
    1104 as libc::c_int as libc::c_short,
    999 as libc::c_int as libc::c_short,
    835 as libc::c_int as libc::c_short,
    564 as libc::c_int as libc::c_short,
    295 as libc::c_int as libc::c_short,
    -(280 as libc::c_int) as libc::c_short,
    -(364 as libc::c_int) as libc::c_short,
    -(340 as libc::c_int) as libc::c_short,
    -(331 as libc::c_int) as libc::c_short,
    -(284 as libc::c_int) as libc::c_short,
    288 as libc::c_int as libc::c_short,
    761 as libc::c_int as libc::c_short,
    880 as libc::c_int as libc::c_short,
    988 as libc::c_int as libc::c_short,
    627 as libc::c_int as libc::c_short,
    146 as libc::c_int as libc::c_short,
    -(226 as libc::c_int) as libc::c_short,
    -(203 as libc::c_int) as libc::c_short,
    -(181 as libc::c_int) as libc::c_short,
    -(142 as libc::c_int) as libc::c_short,
    39 as libc::c_int as libc::c_short,
    24 as libc::c_int as libc::c_short,
    -(26 as libc::c_int) as libc::c_short,
    -(107 as libc::c_int) as libc::c_short,
    -(92 as libc::c_int) as libc::c_short,
    -(161 as libc::c_int) as libc::c_short,
    -(135 as libc::c_int) as libc::c_short,
    -(131 as libc::c_int) as libc::c_short,
    -(88 as libc::c_int) as libc::c_short,
    -(160 as libc::c_int) as libc::c_short,
    -(156 as libc::c_int) as libc::c_short,
    -(75 as libc::c_int) as libc::c_short,
    -(43 as libc::c_int) as libc::c_short,
    -(36 as libc::c_int) as libc::c_short,
    -(6 as libc::c_int) as libc::c_short,
    -(33 as libc::c_int) as libc::c_short,
    33 as libc::c_int as libc::c_short,
    -(324 as libc::c_int) as libc::c_short,
    -(415 as libc::c_int) as libc::c_short,
    -(108 as libc::c_int) as libc::c_short,
    124 as libc::c_int as libc::c_short,
    157 as libc::c_int as libc::c_short,
    191 as libc::c_int as libc::c_short,
    203 as libc::c_int as libc::c_short,
    197 as libc::c_int as libc::c_short,
    144 as libc::c_int as libc::c_short,
    109 as libc::c_int as libc::c_short,
    152 as libc::c_int as libc::c_short,
    176 as libc::c_int as libc::c_short,
    190 as libc::c_int as libc::c_short,
    122 as libc::c_int as libc::c_short,
    101 as libc::c_int as libc::c_short,
    159 as libc::c_int as libc::c_short,
    663 as libc::c_int as libc::c_short,
    668 as libc::c_int as libc::c_short,
    480 as libc::c_int as libc::c_short,
    400 as libc::c_int as libc::c_short,
    379 as libc::c_int as libc::c_short,
    444 as libc::c_int as libc::c_short,
    446 as libc::c_int as libc::c_short,
    458 as libc::c_int as libc::c_short,
    343 as libc::c_int as libc::c_short,
    351 as libc::c_int as libc::c_short,
    310 as libc::c_int as libc::c_short,
    228 as libc::c_int as libc::c_short,
    133 as libc::c_int as libc::c_short,
    44 as libc::c_int as libc::c_short,
    75 as libc::c_int as libc::c_short,
    63 as libc::c_int as libc::c_short,
    -(84 as libc::c_int) as libc::c_short,
    39 as libc::c_int as libc::c_short,
    -(29 as libc::c_int) as libc::c_short,
    35 as libc::c_int as libc::c_short,
    -(94 as libc::c_int) as libc::c_short,
    -(233 as libc::c_int) as libc::c_short,
    -(261 as libc::c_int) as libc::c_short,
    -(354 as libc::c_int) as libc::c_short,
    77 as libc::c_int as libc::c_short,
    262 as libc::c_int as libc::c_short,
    -(24 as libc::c_int) as libc::c_short,
    -(145 as libc::c_int) as libc::c_short,
    -(333 as libc::c_int) as libc::c_short,
    -(409 as libc::c_int) as libc::c_short,
    -(404 as libc::c_int) as libc::c_short,
    -(597 as libc::c_int) as libc::c_short,
    -(488 as libc::c_int) as libc::c_short,
    -(300 as libc::c_int) as libc::c_short,
    910 as libc::c_int as libc::c_short,
    592 as libc::c_int as libc::c_short,
    412 as libc::c_int as libc::c_short,
    120 as libc::c_int as libc::c_short,
    130 as libc::c_int as libc::c_short,
    -(51 as libc::c_int) as libc::c_short,
    -(37 as libc::c_int) as libc::c_short,
    -(77 as libc::c_int) as libc::c_short,
    -(172 as libc::c_int) as libc::c_short,
    -(181 as libc::c_int) as libc::c_short,
    -(159 as libc::c_int) as libc::c_short,
    -(148 as libc::c_int) as libc::c_short,
    -(72 as libc::c_int) as libc::c_short,
    -(62 as libc::c_int) as libc::c_short,
    510 as libc::c_int as libc::c_short,
    516 as libc::c_int as libc::c_short,
    113 as libc::c_int as libc::c_short,
    -(585 as libc::c_int) as libc::c_short,
    -(1075 as libc::c_int) as libc::c_short,
    -(957 as libc::c_int) as libc::c_short,
    -(417 as libc::c_int) as libc::c_short,
    -(195 as libc::c_int) as libc::c_short,
    9 as libc::c_int as libc::c_short,
    7 as libc::c_int as libc::c_short,
    -(88 as libc::c_int) as libc::c_short,
    -(173 as libc::c_int) as libc::c_short,
    -(91 as libc::c_int) as libc::c_short,
    54 as libc::c_int as libc::c_short,
    98 as libc::c_int as libc::c_short,
    95 as libc::c_int as libc::c_short,
    -(28 as libc::c_int) as libc::c_short,
    197 as libc::c_int as libc::c_short,
    -(527 as libc::c_int) as libc::c_short,
    -(621 as libc::c_int) as libc::c_short,
    157 as libc::c_int as libc::c_short,
    122 as libc::c_int as libc::c_short,
    -(168 as libc::c_int) as libc::c_short,
    147 as libc::c_int as libc::c_short,
    309 as libc::c_int as libc::c_short,
    300 as libc::c_int as libc::c_short,
    336 as libc::c_int as libc::c_short,
    315 as libc::c_int as libc::c_short,
    396 as libc::c_int as libc::c_short,
    408 as libc::c_int as libc::c_short,
    376 as libc::c_int as libc::c_short,
    106 as libc::c_int as libc::c_short,
    -(162 as libc::c_int) as libc::c_short,
    -(170 as libc::c_int) as libc::c_short,
    -(315 as libc::c_int) as libc::c_short,
    98 as libc::c_int as libc::c_short,
    821 as libc::c_int as libc::c_short,
    908 as libc::c_int as libc::c_short,
    570 as libc::c_int as libc::c_short,
    -(33 as libc::c_int) as libc::c_short,
    -(312 as libc::c_int) as libc::c_short,
    -(568 as libc::c_int) as libc::c_short,
    -(572 as libc::c_int) as libc::c_short,
    -(378 as libc::c_int) as libc::c_short,
    -(107 as libc::c_int) as libc::c_short,
    23 as libc::c_int as libc::c_short,
    156 as libc::c_int as libc::c_short,
    93 as libc::c_int as libc::c_short,
    -(129 as libc::c_int) as libc::c_short,
    -(87 as libc::c_int) as libc::c_short,
    20 as libc::c_int as libc::c_short,
    -(72 as libc::c_int) as libc::c_short,
    -(37 as libc::c_int) as libc::c_short,
    40 as libc::c_int as libc::c_short,
    21 as libc::c_int as libc::c_short,
    27 as libc::c_int as libc::c_short,
    48 as libc::c_int as libc::c_short,
    75 as libc::c_int as libc::c_short,
    77 as libc::c_int as libc::c_short,
    65 as libc::c_int as libc::c_short,
    46 as libc::c_int as libc::c_short,
    71 as libc::c_int as libc::c_short,
    66 as libc::c_int as libc::c_short,
    47 as libc::c_int as libc::c_short,
    136 as libc::c_int as libc::c_short,
    344 as libc::c_int as libc::c_short,
    236 as libc::c_int as libc::c_short,
    322 as libc::c_int as libc::c_short,
    170 as libc::c_int as libc::c_short,
    283 as libc::c_int as libc::c_short,
    269 as libc::c_int as libc::c_short,
    291 as libc::c_int as libc::c_short,
    162 as libc::c_int as libc::c_short,
    -(43 as libc::c_int) as libc::c_short,
    -(204 as libc::c_int) as libc::c_short,
    -(259 as libc::c_int) as libc::c_short,
    -(240 as libc::c_int) as libc::c_short,
    -(305 as libc::c_int) as libc::c_short,
    -(350 as libc::c_int) as libc::c_short,
    -(312 as libc::c_int) as libc::c_short,
    447 as libc::c_int as libc::c_short,
    348 as libc::c_int as libc::c_short,
    345 as libc::c_int as libc::c_short,
    257 as libc::c_int as libc::c_short,
    71 as libc::c_int as libc::c_short,
    -(131 as libc::c_int) as libc::c_short,
    -(77 as libc::c_int) as libc::c_short,
    -(190 as libc::c_int) as libc::c_short,
    -(202 as libc::c_int) as libc::c_short,
    -(40 as libc::c_int) as libc::c_short,
    35 as libc::c_int as libc::c_short,
    133 as libc::c_int as libc::c_short,
    261 as libc::c_int as libc::c_short,
    365 as libc::c_int as libc::c_short,
    438 as libc::c_int as libc::c_short,
    303 as libc::c_int as libc::c_short,
    -(8 as libc::c_int) as libc::c_short,
    22 as libc::c_int as libc::c_short,
    140 as libc::c_int as libc::c_short,
    137 as libc::c_int as libc::c_short,
    -(300 as libc::c_int) as libc::c_short,
    -(641 as libc::c_int) as libc::c_short,
    -(764 as libc::c_int) as libc::c_short,
    -(268 as libc::c_int) as libc::c_short,
    -(23 as libc::c_int) as libc::c_short,
    -(25 as libc::c_int) as libc::c_short,
    73 as libc::c_int as libc::c_short,
    -(162 as libc::c_int) as libc::c_short,
    -(150 as libc::c_int) as libc::c_short,
    -(212 as libc::c_int) as libc::c_short,
    -(72 as libc::c_int) as libc::c_short,
    6 as libc::c_int as libc::c_short,
    39 as libc::c_int as libc::c_short,
    78 as libc::c_int as libc::c_short,
    104 as libc::c_int as libc::c_short,
    -(93 as libc::c_int) as libc::c_short,
    -(308 as libc::c_int) as libc::c_short,
    -(136 as libc::c_int) as libc::c_short,
    117 as libc::c_int as libc::c_short,
    -(71 as libc::c_int) as libc::c_short,
    -(513 as libc::c_int) as libc::c_short,
    -(820 as libc::c_int) as libc::c_short,
    -(700 as libc::c_int) as libc::c_short,
    -(450 as libc::c_int) as libc::c_short,
    -(161 as libc::c_int) as libc::c_short,
    -(23 as libc::c_int) as libc::c_short,
    29 as libc::c_int as libc::c_short,
    78 as libc::c_int as libc::c_short,
    337 as libc::c_int as libc::c_short,
    106 as libc::c_int as libc::c_short,
    -(406 as libc::c_int) as libc::c_short,
    -(782 as libc::c_int) as libc::c_short,
    -(112 as libc::c_int) as libc::c_short,
    233 as libc::c_int as libc::c_short,
    383 as libc::c_int as libc::c_short,
    62 as libc::c_int as libc::c_short,
    -(126 as libc::c_int) as libc::c_short,
    6 as libc::c_int as libc::c_short,
    -(77 as libc::c_int) as libc::c_short,
    -(29 as libc::c_int) as libc::c_short,
    -(146 as libc::c_int) as libc::c_short,
    -(123 as libc::c_int) as libc::c_short,
    -(51 as libc::c_int) as libc::c_short,
    -(27 as libc::c_int) as libc::c_short,
    -(27 as libc::c_int) as libc::c_short,
    -(381 as libc::c_int) as libc::c_short,
    -(641 as libc::c_int) as libc::c_short,
    402 as libc::c_int as libc::c_short,
    539 as libc::c_int as libc::c_short,
    8 as libc::c_int as libc::c_short,
    -(207 as libc::c_int) as libc::c_short,
    -(366 as libc::c_int) as libc::c_short,
    -(36 as libc::c_int) as libc::c_short,
    -(27 as libc::c_int) as libc::c_short,
    -(204 as libc::c_int) as libc::c_short,
    -(227 as libc::c_int) as libc::c_short,
    -(237 as libc::c_int) as libc::c_short,
    -(189 as libc::c_int) as libc::c_short,
    -(64 as libc::c_int) as libc::c_short,
    51 as libc::c_int as libc::c_short,
    -(92 as libc::c_int) as libc::c_short,
    -(137 as libc::c_int) as libc::c_short,
    -(281 as libc::c_int) as libc::c_short,
    62 as libc::c_int as libc::c_short,
    233 as libc::c_int as libc::c_short,
    92 as libc::c_int as libc::c_short,
    148 as libc::c_int as libc::c_short,
    294 as libc::c_int as libc::c_short,
    363 as libc::c_int as libc::c_short,
    416 as libc::c_int as libc::c_short,
    564 as libc::c_int as libc::c_short,
    625 as libc::c_int as libc::c_short,
    370 as libc::c_int as libc::c_short,
    -(36 as libc::c_int) as libc::c_short,
    -(469 as libc::c_int) as libc::c_short,
    -(462 as libc::c_int) as libc::c_short,
    102 as libc::c_int as libc::c_short,
    168 as libc::c_int as libc::c_short,
    32 as libc::c_int as libc::c_short,
    117 as libc::c_int as libc::c_short,
    -(21 as libc::c_int) as libc::c_short,
    97 as libc::c_int as libc::c_short,
    139 as libc::c_int as libc::c_short,
    89 as libc::c_int as libc::c_short,
    104 as libc::c_int as libc::c_short,
    35 as libc::c_int as libc::c_short,
    4 as libc::c_int as libc::c_short,
    82 as libc::c_int as libc::c_short,
    66 as libc::c_int as libc::c_short,
    58 as libc::c_int as libc::c_short,
    73 as libc::c_int as libc::c_short,
    93 as libc::c_int as libc::c_short,
    -(76 as libc::c_int) as libc::c_short,
    -(320 as libc::c_int) as libc::c_short,
    -(236 as libc::c_int) as libc::c_short,
    -(189 as libc::c_int) as libc::c_short,
    -(203 as libc::c_int) as libc::c_short,
    -(142 as libc::c_int) as libc::c_short,
    -(27 as libc::c_int) as libc::c_short,
    -(73 as libc::c_int) as libc::c_short,
    9 as libc::c_int as libc::c_short,
    -(9 as libc::c_int) as libc::c_short,
    -(25 as libc::c_int) as libc::c_short,
    12 as libc::c_int as libc::c_short,
    -(15 as libc::c_int) as libc::c_short,
    4 as libc::c_int as libc::c_short,
    4 as libc::c_int as libc::c_short,
    -(50 as libc::c_int) as libc::c_short,
    314 as libc::c_int as libc::c_short,
    180 as libc::c_int as libc::c_short,
    162 as libc::c_int as libc::c_short,
    -(49 as libc::c_int) as libc::c_short,
    199 as libc::c_int as libc::c_short,
    -(108 as libc::c_int) as libc::c_short,
    -(227 as libc::c_int) as libc::c_short,
    -(66 as libc::c_int) as libc::c_short,
    -(447 as libc::c_int) as libc::c_short,
    -(67 as libc::c_int) as libc::c_short,
    -(264 as libc::c_int) as libc::c_short,
    -(394 as libc::c_int) as libc::c_short,
    5 as libc::c_int as libc::c_short,
    55 as libc::c_int as libc::c_short,
    -(133 as libc::c_int) as libc::c_short,
    -(176 as libc::c_int) as libc::c_short,
    -(116 as libc::c_int) as libc::c_short,
    -(241 as libc::c_int) as libc::c_short,
    272 as libc::c_int as libc::c_short,
    109 as libc::c_int as libc::c_short,
    282 as libc::c_int as libc::c_short,
    262 as libc::c_int as libc::c_short,
    192 as libc::c_int as libc::c_short,
    -(64 as libc::c_int) as libc::c_short,
    -(392 as libc::c_int) as libc::c_short,
    -(514 as libc::c_int) as libc::c_short,
    156 as libc::c_int as libc::c_short,
    203 as libc::c_int as libc::c_short,
    154 as libc::c_int as libc::c_short,
    72 as libc::c_int as libc::c_short,
    -(34 as libc::c_int) as libc::c_short,
    -(160 as libc::c_int) as libc::c_short,
    -(73 as libc::c_int) as libc::c_short,
    3 as libc::c_int as libc::c_short,
    -(33 as libc::c_int) as libc::c_short,
    -(431 as libc::c_int) as libc::c_short,
    321 as libc::c_int as libc::c_short,
    18 as libc::c_int as libc::c_short,
    -(567 as libc::c_int) as libc::c_short,
    -(590 as libc::c_int) as libc::c_short,
    -(108 as libc::c_int) as libc::c_short,
    88 as libc::c_int as libc::c_short,
    66 as libc::c_int as libc::c_short,
    51 as libc::c_int as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    -(193 as libc::c_int) as libc::c_short,
    -(46 as libc::c_int) as libc::c_short,
    65 as libc::c_int as libc::c_short,
    -(29 as libc::c_int) as libc::c_short,
    -(23 as libc::c_int) as libc::c_short,
    215 as libc::c_int as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    101 as libc::c_int as libc::c_short,
    -(113 as libc::c_int) as libc::c_short,
    32 as libc::c_int as libc::c_short,
    304 as libc::c_int as libc::c_short,
    88 as libc::c_int as libc::c_short,
    320 as libc::c_int as libc::c_short,
    448 as libc::c_int as libc::c_short,
    5 as libc::c_int as libc::c_short,
    -(439 as libc::c_int) as libc::c_short,
    -(562 as libc::c_int) as libc::c_short,
    -(508 as libc::c_int) as libc::c_short,
    -(135 as libc::c_int) as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    -(171 as libc::c_int) as libc::c_short,
    -(8 as libc::c_int) as libc::c_short,
    182 as libc::c_int as libc::c_short,
    -(99 as libc::c_int) as libc::c_short,
    -(181 as libc::c_int) as libc::c_short,
    -(149 as libc::c_int) as libc::c_short,
    376 as libc::c_int as libc::c_short,
    476 as libc::c_int as libc::c_short,
    64 as libc::c_int as libc::c_short,
    -(396 as libc::c_int) as libc::c_short,
    -(652 as libc::c_int) as libc::c_short,
    -(150 as libc::c_int) as libc::c_short,
    176 as libc::c_int as libc::c_short,
    222 as libc::c_int as libc::c_short,
    65 as libc::c_int as libc::c_short,
    -(590 as libc::c_int) as libc::c_short,
    719 as libc::c_int as libc::c_short,
    271 as libc::c_int as libc::c_short,
    399 as libc::c_int as libc::c_short,
    245 as libc::c_int as libc::c_short,
    72 as libc::c_int as libc::c_short,
    -(156 as libc::c_int) as libc::c_short,
    -(152 as libc::c_int) as libc::c_short,
    -(176 as libc::c_int) as libc::c_short,
    59 as libc::c_int as libc::c_short,
    94 as libc::c_int as libc::c_short,
    125 as libc::c_int as libc::c_short,
    -(9 as libc::c_int) as libc::c_short,
    -(7 as libc::c_int) as libc::c_short,
    9 as libc::c_int as libc::c_short,
    1 as libc::c_int as libc::c_short,
    -(61 as libc::c_int) as libc::c_short,
    -(116 as libc::c_int) as libc::c_short,
    -(82 as libc::c_int) as libc::c_short,
    1 as libc::c_int as libc::c_short,
    79 as libc::c_int as libc::c_short,
    22 as libc::c_int as libc::c_short,
    -(44 as libc::c_int) as libc::c_short,
    -(15 as libc::c_int) as libc::c_short,
    -(48 as libc::c_int) as libc::c_short,
    -(65 as libc::c_int) as libc::c_short,
    -(62 as libc::c_int) as libc::c_short,
    -(101 as libc::c_int) as libc::c_short,
    -(102 as libc::c_int) as libc::c_short,
    -(54 as libc::c_int) as libc::c_short,
    -(70 as libc::c_int) as libc::c_short,
    -(78 as libc::c_int) as libc::c_short,
    -(80 as libc::c_int) as libc::c_short,
    -(25 as libc::c_int) as libc::c_short,
    398 as libc::c_int as libc::c_short,
    71 as libc::c_int as libc::c_short,
    139 as libc::c_int as libc::c_short,
    38 as libc::c_int as libc::c_short,
    90 as libc::c_int as libc::c_short,
    194 as libc::c_int as libc::c_short,
    222 as libc::c_int as libc::c_short,
    249 as libc::c_int as libc::c_short,
    165 as libc::c_int as libc::c_short,
    94 as libc::c_int as libc::c_short,
    221 as libc::c_int as libc::c_short,
    262 as libc::c_int as libc::c_short,
    163 as libc::c_int as libc::c_short,
    91 as libc::c_int as libc::c_short,
    -(206 as libc::c_int) as libc::c_short,
    573 as libc::c_int as libc::c_short,
    200 as libc::c_int as libc::c_short,
    -(287 as libc::c_int) as libc::c_short,
    -(147 as libc::c_int) as libc::c_short,
    5 as libc::c_int as libc::c_short,
    -(18 as libc::c_int) as libc::c_short,
    -(85 as libc::c_int) as libc::c_short,
    -(74 as libc::c_int) as libc::c_short,
    -(125 as libc::c_int) as libc::c_short,
    -(87 as libc::c_int) as libc::c_short,
    85 as libc::c_int as libc::c_short,
    141 as libc::c_int as libc::c_short,
    4 as libc::c_int as libc::c_short,
    -(4 as libc::c_int) as libc::c_short,
    28 as libc::c_int as libc::c_short,
    234 as libc::c_int as libc::c_short,
    48 as libc::c_int as libc::c_short,
    -(150 as libc::c_int) as libc::c_short,
    -(111 as libc::c_int) as libc::c_short,
    -(506 as libc::c_int) as libc::c_short,
    237 as libc::c_int as libc::c_short,
    -(209 as libc::c_int) as libc::c_short,
    345 as libc::c_int as libc::c_short,
    94 as libc::c_int as libc::c_short,
    -(124 as libc::c_int) as libc::c_short,
    77 as libc::c_int as libc::c_short,
    121 as libc::c_int as libc::c_short,
    143 as libc::c_int as libc::c_short,
    12 as libc::c_int as libc::c_short,
    -(80 as libc::c_int) as libc::c_short,
    -(48 as libc::c_int) as libc::c_short,
    191 as libc::c_int as libc::c_short,
    144 as libc::c_int as libc::c_short,
    -(93 as libc::c_int) as libc::c_short,
    -(65 as libc::c_int) as libc::c_short,
    -(151 as libc::c_int) as libc::c_short,
    -(643 as libc::c_int) as libc::c_short,
    435 as libc::c_int as libc::c_short,
    106 as libc::c_int as libc::c_short,
    87 as libc::c_int as libc::c_short,
    7 as libc::c_int as libc::c_short,
    65 as libc::c_int as libc::c_short,
    102 as libc::c_int as libc::c_short,
    94 as libc::c_int as libc::c_short,
    68 as libc::c_int as libc::c_short,
    5 as libc::c_int as libc::c_short,
    99 as libc::c_int as libc::c_short,
    222 as libc::c_int as libc::c_short,
    93 as libc::c_int as libc::c_short,
    94 as libc::c_int as libc::c_short,
    355 as libc::c_int as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    -(89 as libc::c_int) as libc::c_short,
    -(228 as libc::c_int) as libc::c_short,
    -(503 as libc::c_int) as libc::c_short,
    287 as libc::c_int as libc::c_short,
    109 as libc::c_int as libc::c_short,
    108 as libc::c_int as libc::c_short,
    449 as libc::c_int as libc::c_short,
    253 as libc::c_int as libc::c_short,
    -(29 as libc::c_int) as libc::c_short,
    -(109 as libc::c_int) as libc::c_short,
    -(116 as libc::c_int) as libc::c_short,
    15 as libc::c_int as libc::c_short,
    -(73 as libc::c_int) as libc::c_short,
    -(20 as libc::c_int) as libc::c_short,
    131 as libc::c_int as libc::c_short,
    -(147 as libc::c_int) as libc::c_short,
    72 as libc::c_int as libc::c_short,
    59 as libc::c_int as libc::c_short,
    -(150 as libc::c_int) as libc::c_short,
    -(594 as libc::c_int) as libc::c_short,
    273 as libc::c_int as libc::c_short,
    316 as libc::c_int as libc::c_short,
    132 as libc::c_int as libc::c_short,
    199 as libc::c_int as libc::c_short,
    106 as libc::c_int as libc::c_short,
    198 as libc::c_int as libc::c_short,
    212 as libc::c_int as libc::c_short,
    220 as libc::c_int as libc::c_short,
    82 as libc::c_int as libc::c_short,
    45 as libc::c_int as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    223 as libc::c_int as libc::c_short,
    137 as libc::c_int as libc::c_short,
    270 as libc::c_int as libc::c_short,
    38 as libc::c_int as libc::c_short,
    252 as libc::c_int as libc::c_short,
    135 as libc::c_int as libc::c_short,
    -(177 as libc::c_int) as libc::c_short,
    -(207 as libc::c_int) as libc::c_short,
    -(360 as libc::c_int) as libc::c_short,
    -(102 as libc::c_int) as libc::c_short,
    403 as libc::c_int as libc::c_short,
    406 as libc::c_int as libc::c_short,
    -(14 as libc::c_int) as libc::c_short,
    83 as libc::c_int as libc::c_short,
    64 as libc::c_int as libc::c_short,
    51 as libc::c_int as libc::c_short,
    -(7 as libc::c_int) as libc::c_short,
    -(99 as libc::c_int) as libc::c_short,
    -(97 as libc::c_int) as libc::c_short,
    -(88 as libc::c_int) as libc::c_short,
    -(124 as libc::c_int) as libc::c_short,
    -(65 as libc::c_int) as libc::c_short,
    42 as libc::c_int as libc::c_short,
    32 as libc::c_int as libc::c_short,
    28 as libc::c_int as libc::c_short,
    29 as libc::c_int as libc::c_short,
    12 as libc::c_int as libc::c_short,
    20 as libc::c_int as libc::c_short,
    119 as libc::c_int as libc::c_short,
    -(26 as libc::c_int) as libc::c_short,
    -(212 as libc::c_int) as libc::c_short,
    -(201 as libc::c_int) as libc::c_short,
    373 as libc::c_int as libc::c_short,
    251 as libc::c_int as libc::c_short,
    141 as libc::c_int as libc::c_short,
    103 as libc::c_int as libc::c_short,
    36 as libc::c_int as libc::c_short,
    -(52 as libc::c_int) as libc::c_short,
    66 as libc::c_int as libc::c_short,
    18 as libc::c_int as libc::c_short,
    -(6 as libc::c_int) as libc::c_short,
    -(95 as libc::c_int) as libc::c_short,
    -(196 as libc::c_int) as libc::c_short,
    5 as libc::c_int as libc::c_short,
    98 as libc::c_int as libc::c_short,
    -(85 as libc::c_int) as libc::c_short,
    -(108 as libc::c_int) as libc::c_short,
    218 as libc::c_int as libc::c_short,
    -(164 as libc::c_int) as libc::c_short,
    20 as libc::c_int as libc::c_short,
    356 as libc::c_int as libc::c_short,
    172 as libc::c_int as libc::c_short,
    37 as libc::c_int as libc::c_short,
    266 as libc::c_int as libc::c_short,
    23 as libc::c_int as libc::c_short,
    112 as libc::c_int as libc::c_short,
    -(24 as libc::c_int) as libc::c_short,
    -(99 as libc::c_int) as libc::c_short,
    -(92 as libc::c_int) as libc::c_short,
    -(178 as libc::c_int) as libc::c_short,
    29 as libc::c_int as libc::c_short,
    -(278 as libc::c_int) as libc::c_short,
    388 as libc::c_int as libc::c_short,
    -(60 as libc::c_int) as libc::c_short,
    -(220 as libc::c_int) as libc::c_short,
    300 as libc::c_int as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    154 as libc::c_int as libc::c_short,
    191 as libc::c_int as libc::c_short,
    15 as libc::c_int as libc::c_short,
    -(37 as libc::c_int) as libc::c_short,
    -(110 as libc::c_int) as libc::c_short,
    -(153 as libc::c_int) as libc::c_short,
    -(150 as libc::c_int) as libc::c_short,
    -(114 as libc::c_int) as libc::c_short,
    -(7 as libc::c_int) as libc::c_short,
    -(94 as libc::c_int) as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    -(62 as libc::c_int) as libc::c_short,
    -(177 as libc::c_int) as libc::c_short,
    4 as libc::c_int as libc::c_short,
    -(70 as libc::c_int) as libc::c_short,
    35 as libc::c_int as libc::c_short,
    453 as libc::c_int as libc::c_short,
    147 as libc::c_int as libc::c_short,
    -(247 as libc::c_int) as libc::c_short,
    -(328 as libc::c_int) as libc::c_short,
    101 as libc::c_int as libc::c_short,
    20 as libc::c_int as libc::c_short,
    -(114 as libc::c_int) as libc::c_short,
    147 as libc::c_int as libc::c_short,
    108 as libc::c_int as libc::c_short,
    -(119 as libc::c_int) as libc::c_short,
    -(109 as libc::c_int) as libc::c_short,
    -(102 as libc::c_int) as libc::c_short,
    -(238 as libc::c_int) as libc::c_short,
    55 as libc::c_int as libc::c_short,
    -(102 as libc::c_int) as libc::c_short,
    173 as libc::c_int as libc::c_short,
    -(89 as libc::c_int) as libc::c_short,
    129 as libc::c_int as libc::c_short,
    138 as libc::c_int as libc::c_short,
    -(330 as libc::c_int) as libc::c_short,
    -(160 as libc::c_int) as libc::c_short,
    485 as libc::c_int as libc::c_short,
    154 as libc::c_int as libc::c_short,
    -(59 as libc::c_int) as libc::c_short,
    -(170 as libc::c_int) as libc::c_short,
    -(20 as libc::c_int) as libc::c_short,
    -(34 as libc::c_int) as libc::c_short,
    -(261 as libc::c_int) as libc::c_short,
    -(40 as libc::c_int) as libc::c_short,
    -(129 as libc::c_int) as libc::c_short,
    77 as libc::c_int as libc::c_short,
    -(84 as libc::c_int) as libc::c_short,
    69 as libc::c_int as libc::c_short,
    83 as libc::c_int as libc::c_short,
    160 as libc::c_int as libc::c_short,
    169 as libc::c_int as libc::c_short,
    63 as libc::c_int as libc::c_short,
    -(516 as libc::c_int) as libc::c_short,
    30 as libc::c_int as libc::c_short,
    336 as libc::c_int as libc::c_short,
    52 as libc::c_int as libc::c_short,
    -(0 as libc::c_int) as libc::c_short,
    -(52 as libc::c_int) as libc::c_short,
    -(124 as libc::c_int) as libc::c_short,
    158 as libc::c_int as libc::c_short,
    19 as libc::c_int as libc::c_short,
    197 as libc::c_int as libc::c_short,
    -(10 as libc::c_int) as libc::c_short,
    -(375 as libc::c_int) as libc::c_short,
    405 as libc::c_int as libc::c_short,
    285 as libc::c_int as libc::c_short,
    114 as libc::c_int as libc::c_short,
    -(395 as libc::c_int) as libc::c_short,
    -(47 as libc::c_int) as libc::c_short,
    196 as libc::c_int as libc::c_short,
    62 as libc::c_int as libc::c_short,
    87 as libc::c_int as libc::c_short,
    -(106 as libc::c_int) as libc::c_short,
    -(65 as libc::c_int) as libc::c_short,
    -(75 as libc::c_int) as libc::c_short,
    -(69 as libc::c_int) as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    34 as libc::c_int as libc::c_short,
    99 as libc::c_int as libc::c_short,
    59 as libc::c_int as libc::c_short,
    83 as libc::c_int as libc::c_short,
    98 as libc::c_int as libc::c_short,
    44 as libc::c_int as libc::c_short,
    0 as libc::c_int as libc::c_short,
    24 as libc::c_int as libc::c_short,
    18 as libc::c_int as libc::c_short,
    17 as libc::c_int as libc::c_short,
    70 as libc::c_int as libc::c_short,
    -(22 as libc::c_int) as libc::c_short,
    194 as libc::c_int as libc::c_short,
    208 as libc::c_int as libc::c_short,
    144 as libc::c_int as libc::c_short,
    -(79 as libc::c_int) as libc::c_short,
    -(15 as libc::c_int) as libc::c_short,
    32 as libc::c_int as libc::c_short,
    -(104 as libc::c_int) as libc::c_short,
    -(28 as libc::c_int) as libc::c_short,
    -(105 as libc::c_int) as libc::c_short,
    -(186 as libc::c_int) as libc::c_short,
    -(212 as libc::c_int) as libc::c_short,
    -(228 as libc::c_int) as libc::c_short,
    -(79 as libc::c_int) as libc::c_short,
    -(76 as libc::c_int) as libc::c_short,
    51 as libc::c_int as libc::c_short,
    -(71 as libc::c_int) as libc::c_short,
    72 as libc::c_int as libc::c_short,
    118 as libc::c_int as libc::c_short,
    -(34 as libc::c_int) as libc::c_short,
    -(3 as libc::c_int) as libc::c_short,
    -(171 as libc::c_int) as libc::c_short,
    5 as libc::c_int as libc::c_short,
    2 as libc::c_int as libc::c_short,
    -(108 as libc::c_int) as libc::c_short,
    -(125 as libc::c_int) as libc::c_short,
    62 as libc::c_int as libc::c_short,
    -(58 as libc::c_int) as libc::c_short,
    58 as libc::c_int as libc::c_short,
    -(121 as libc::c_int) as libc::c_short,
    73 as libc::c_int as libc::c_short,
    -(466 as libc::c_int) as libc::c_short,
    92 as libc::c_int as libc::c_short,
    63 as libc::c_int as libc::c_short,
    -(94 as libc::c_int) as libc::c_short,
    -(78 as libc::c_int) as libc::c_short,
    -(76 as libc::c_int) as libc::c_short,
    212 as libc::c_int as libc::c_short,
    36 as libc::c_int as libc::c_short,
    -(225 as libc::c_int) as libc::c_short,
    -(71 as libc::c_int) as libc::c_short,
    -(354 as libc::c_int) as libc::c_short,
    152 as libc::c_int as libc::c_short,
    143 as libc::c_int as libc::c_short,
    -(79 as libc::c_int) as libc::c_short,
    -(246 as libc::c_int) as libc::c_short,
    -(51 as libc::c_int) as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    -(6 as libc::c_int) as libc::c_short,
    -(270 as libc::c_int) as libc::c_short,
    240 as libc::c_int as libc::c_short,
    210 as libc::c_int as libc::c_short,
    30 as libc::c_int as libc::c_short,
    -(157 as libc::c_int) as libc::c_short,
    -(231 as libc::c_int) as libc::c_short,
    74 as libc::c_int as libc::c_short,
    -(146 as libc::c_int) as libc::c_short,
    88 as libc::c_int as libc::c_short,
    -(273 as libc::c_int) as libc::c_short,
    156 as libc::c_int as libc::c_short,
    92 as libc::c_int as libc::c_short,
    56 as libc::c_int as libc::c_short,
    71 as libc::c_int as libc::c_short,
    2 as libc::c_int as libc::c_short,
    318 as libc::c_int as libc::c_short,
    164 as libc::c_int as libc::c_short,
    32 as libc::c_int as libc::c_short,
    -(110 as libc::c_int) as libc::c_short,
    -(35 as libc::c_int) as libc::c_short,
    -(41 as libc::c_int) as libc::c_short,
    -(95 as libc::c_int) as libc::c_short,
    -(106 as libc::c_int) as libc::c_short,
    11 as libc::c_int as libc::c_short,
    132 as libc::c_int as libc::c_short,
    -(68 as libc::c_int) as libc::c_short,
    55 as libc::c_int as libc::c_short,
    123 as libc::c_int as libc::c_short,
    -(83 as libc::c_int) as libc::c_short,
    -(149 as libc::c_int) as libc::c_short,
    212 as libc::c_int as libc::c_short,
    132 as libc::c_int as libc::c_short,
    0 as libc::c_int as libc::c_short,
    -(194 as libc::c_int) as libc::c_short,
    55 as libc::c_int as libc::c_short,
    206 as libc::c_int as libc::c_short,
    -(108 as libc::c_int) as libc::c_short,
    -(353 as libc::c_int) as libc::c_short,
    289 as libc::c_int as libc::c_short,
    -(195 as libc::c_int) as libc::c_short,
    1 as libc::c_int as libc::c_short,
    233 as libc::c_int as libc::c_short,
    -(22 as libc::c_int) as libc::c_short,
    -(60 as libc::c_int) as libc::c_short,
    20 as libc::c_int as libc::c_short,
    26 as libc::c_int as libc::c_short,
    68 as libc::c_int as libc::c_short,
    166 as libc::c_int as libc::c_short,
    27 as libc::c_int as libc::c_short,
    -(58 as libc::c_int) as libc::c_short,
    130 as libc::c_int as libc::c_short,
    112 as libc::c_int as libc::c_short,
    107 as libc::c_int as libc::c_short,
    27 as libc::c_int as libc::c_short,
    -(165 as libc::c_int) as libc::c_short,
    115 as libc::c_int as libc::c_short,
    -(93 as libc::c_int) as libc::c_short,
    -(37 as libc::c_int) as libc::c_short,
    38 as libc::c_int as libc::c_short,
    83 as libc::c_int as libc::c_short,
    483 as libc::c_int as libc::c_short,
    65 as libc::c_int as libc::c_short,
    -(229 as libc::c_int) as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    157 as libc::c_int as libc::c_short,
    85 as libc::c_int as libc::c_short,
    50 as libc::c_int as libc::c_short,
    136 as libc::c_int as libc::c_short,
    10 as libc::c_int as libc::c_short,
    32 as libc::c_int as libc::c_short,
    83 as libc::c_int as libc::c_short,
    82 as libc::c_int as libc::c_short,
    55 as libc::c_int as libc::c_short,
    5 as libc::c_int as libc::c_short,
    -(9 as libc::c_int) as libc::c_short,
    -(52 as libc::c_int) as libc::c_short,
    -(78 as libc::c_int) as libc::c_short,
    -(81 as libc::c_int) as libc::c_short,
    -(51 as libc::c_int) as libc::c_short,
    40 as libc::c_int as libc::c_short,
    18 as libc::c_int as libc::c_short,
    -(127 as libc::c_int) as libc::c_short,
    -(224 as libc::c_int) as libc::c_short,
    -(41 as libc::c_int) as libc::c_short,
    53 as libc::c_int as libc::c_short,
    -(210 as libc::c_int) as libc::c_short,
    -(113 as libc::c_int) as libc::c_short,
    24 as libc::c_int as libc::c_short,
    -(17 as libc::c_int) as libc::c_short,
    -(187 as libc::c_int) as libc::c_short,
    -(89 as libc::c_int) as libc::c_short,
    8 as libc::c_int as libc::c_short,
    121 as libc::c_int as libc::c_short,
    83 as libc::c_int as libc::c_short,
    77 as libc::c_int as libc::c_short,
    91 as libc::c_int as libc::c_short,
    -(74 as libc::c_int) as libc::c_short,
    -(35 as libc::c_int) as libc::c_short,
    -(112 as libc::c_int) as libc::c_short,
    -(161 as libc::c_int) as libc::c_short,
    -(173 as libc::c_int) as libc::c_short,
    102 as libc::c_int as libc::c_short,
    132 as libc::c_int as libc::c_short,
    -(125 as libc::c_int) as libc::c_short,
    -(61 as libc::c_int) as libc::c_short,
    103 as libc::c_int as libc::c_short,
    -(260 as libc::c_int) as libc::c_short,
    52 as libc::c_int as libc::c_short,
    166 as libc::c_int as libc::c_short,
    -(32 as libc::c_int) as libc::c_short,
    -(156 as libc::c_int) as libc::c_short,
    -(87 as libc::c_int) as libc::c_short,
    -(56 as libc::c_int) as libc::c_short,
    60 as libc::c_int as libc::c_short,
    -(70 as libc::c_int) as libc::c_short,
    -(124 as libc::c_int) as libc::c_short,
    242 as libc::c_int as libc::c_short,
    114 as libc::c_int as libc::c_short,
    -(251 as libc::c_int) as libc::c_short,
    -(166 as libc::c_int) as libc::c_short,
    201 as libc::c_int as libc::c_short,
    127 as libc::c_int as libc::c_short,
    28 as libc::c_int as libc::c_short,
    -(11 as libc::c_int) as libc::c_short,
    23 as libc::c_int as libc::c_short,
    -(80 as libc::c_int) as libc::c_short,
    -(115 as libc::c_int) as libc::c_short,
    -(20 as libc::c_int) as libc::c_short,
    -(51 as libc::c_int) as libc::c_short,
    -(348 as libc::c_int) as libc::c_short,
    340 as libc::c_int as libc::c_short,
    -(34 as libc::c_int) as libc::c_short,
    133 as libc::c_int as libc::c_short,
    13 as libc::c_int as libc::c_short,
    92 as libc::c_int as libc::c_short,
    -(124 as libc::c_int) as libc::c_short,
    -(136 as libc::c_int) as libc::c_short,
    -(120 as libc::c_int) as libc::c_short,
    -(26 as libc::c_int) as libc::c_short,
    -(6 as libc::c_int) as libc::c_short,
    17 as libc::c_int as libc::c_short,
    28 as libc::c_int as libc::c_short,
    21 as libc::c_int as libc::c_short,
    120 as libc::c_int as libc::c_short,
    -(168 as libc::c_int) as libc::c_short,
    160 as libc::c_int as libc::c_short,
    -(35 as libc::c_int) as libc::c_short,
    115 as libc::c_int as libc::c_short,
    28 as libc::c_int as libc::c_short,
    9 as libc::c_int as libc::c_short,
    7 as libc::c_int as libc::c_short,
    -(56 as libc::c_int) as libc::c_short,
    39 as libc::c_int as libc::c_short,
    156 as libc::c_int as libc::c_short,
    256 as libc::c_int as libc::c_short,
    -(18 as libc::c_int) as libc::c_short,
    1 as libc::c_int as libc::c_short,
    277 as libc::c_int as libc::c_short,
    82 as libc::c_int as libc::c_short,
    -(70 as libc::c_int) as libc::c_short,
    -(144 as libc::c_int) as libc::c_short,
    -(88 as libc::c_int) as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    -(59 as libc::c_int) as libc::c_short,
    -(157 as libc::c_int) as libc::c_short,
    8 as libc::c_int as libc::c_short,
    -(134 as libc::c_int) as libc::c_short,
    21 as libc::c_int as libc::c_short,
    -(40 as libc::c_int) as libc::c_short,
    58 as libc::c_int as libc::c_short,
    -(21 as libc::c_int) as libc::c_short,
    194 as libc::c_int as libc::c_short,
    -(276 as libc::c_int) as libc::c_short,
    97 as libc::c_int as libc::c_short,
    279 as libc::c_int as libc::c_short,
    -(56 as libc::c_int) as libc::c_short,
    -(140 as libc::c_int) as libc::c_short,
    125 as libc::c_int as libc::c_short,
    57 as libc::c_int as libc::c_short,
    -(184 as libc::c_int) as libc::c_short,
    -(204 as libc::c_int) as libc::c_short,
    -(70 as libc::c_int) as libc::c_short,
    -(2 as libc::c_int) as libc::c_short,
    128 as libc::c_int as libc::c_short,
    -(202 as libc::c_int) as libc::c_short,
    -(78 as libc::c_int) as libc::c_short,
    230 as libc::c_int as libc::c_short,
    -(23 as libc::c_int) as libc::c_short,
    161 as libc::c_int as libc::c_short,
    -(102 as libc::c_int) as libc::c_short,
    1 as libc::c_int as libc::c_short,
    1 as libc::c_int as libc::c_short,
    180 as libc::c_int as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    -(86 as libc::c_int) as libc::c_short,
    -(167 as libc::c_int) as libc::c_short,
    -(57 as libc::c_int) as libc::c_short,
    -(60 as libc::c_int) as libc::c_short,
    27 as libc::c_int as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    99 as libc::c_int as libc::c_short,
    108 as libc::c_int as libc::c_short,
    111 as libc::c_int as libc::c_short,
    76 as libc::c_int as libc::c_short,
    69 as libc::c_int as libc::c_short,
    34 as libc::c_int as libc::c_short,
    -(21 as libc::c_int) as libc::c_short,
    53 as libc::c_int as libc::c_short,
    38 as libc::c_int as libc::c_short,
    34 as libc::c_int as libc::c_short,
    78 as libc::c_int as libc::c_short,
    73 as libc::c_int as libc::c_short,
    219 as libc::c_int as libc::c_short,
    51 as libc::c_int as libc::c_short,
    15 as libc::c_int as libc::c_short,
    -(72 as libc::c_int) as libc::c_short,
    -(103 as libc::c_int) as libc::c_short,
    -(207 as libc::c_int) as libc::c_short,
    30 as libc::c_int as libc::c_short,
    213 as libc::c_int as libc::c_short,
    -(14 as libc::c_int) as libc::c_short,
    31 as libc::c_int as libc::c_short,
    -(94 as libc::c_int) as libc::c_short,
    -(40 as libc::c_int) as libc::c_short,
    -(144 as libc::c_int) as libc::c_short,
    67 as libc::c_int as libc::c_short,
    4 as libc::c_int as libc::c_short,
    105 as libc::c_int as libc::c_short,
    59 as libc::c_int as libc::c_short,
    -(240 as libc::c_int) as libc::c_short,
    25 as libc::c_int as libc::c_short,
    244 as libc::c_int as libc::c_short,
    69 as libc::c_int as libc::c_short,
    58 as libc::c_int as libc::c_short,
    23 as libc::c_int as libc::c_short,
    -(24 as libc::c_int) as libc::c_short,
    -(5 as libc::c_int) as libc::c_short,
    -(15 as libc::c_int) as libc::c_short,
    -(133 as libc::c_int) as libc::c_short,
    -(71 as libc::c_int) as libc::c_short,
    -(67 as libc::c_int) as libc::c_short,
    181 as libc::c_int as libc::c_short,
    29 as libc::c_int as libc::c_short,
    -(45 as libc::c_int) as libc::c_short,
    121 as libc::c_int as libc::c_short,
    96 as libc::c_int as libc::c_short,
    51 as libc::c_int as libc::c_short,
    -(72 as libc::c_int) as libc::c_short,
    -(53 as libc::c_int) as libc::c_short,
    56 as libc::c_int as libc::c_short,
    -(153 as libc::c_int) as libc::c_short,
    -(27 as libc::c_int) as libc::c_short,
    85 as libc::c_int as libc::c_short,
    183 as libc::c_int as libc::c_short,
    211 as libc::c_int as libc::c_short,
    105 as libc::c_int as libc::c_short,
    -(34 as libc::c_int) as libc::c_short,
    -(46 as libc::c_int) as libc::c_short,
    43 as libc::c_int as libc::c_short,
    -(72 as libc::c_int) as libc::c_short,
    -(93 as libc::c_int) as libc::c_short,
    36 as libc::c_int as libc::c_short,
    -(128 as libc::c_int) as libc::c_short,
    29 as libc::c_int as libc::c_short,
    111 as libc::c_int as libc::c_short,
    -(95 as libc::c_int) as libc::c_short,
    -(156 as libc::c_int) as libc::c_short,
    -(179 as libc::c_int) as libc::c_short,
    -(235 as libc::c_int) as libc::c_short,
    21 as libc::c_int as libc::c_short,
    -(39 as libc::c_int) as libc::c_short,
    -(71 as libc::c_int) as libc::c_short,
    -(33 as libc::c_int) as libc::c_short,
    -(61 as libc::c_int) as libc::c_short,
    -(252 as libc::c_int) as libc::c_short,
    230 as libc::c_int as libc::c_short,
    -(131 as libc::c_int) as libc::c_short,
    157 as libc::c_int as libc::c_short,
    -(21 as libc::c_int) as libc::c_short,
    -(85 as libc::c_int) as libc::c_short,
    -(28 as libc::c_int) as libc::c_short,
    -(123 as libc::c_int) as libc::c_short,
    80 as libc::c_int as libc::c_short,
    -(160 as libc::c_int) as libc::c_short,
    63 as libc::c_int as libc::c_short,
    47 as libc::c_int as libc::c_short,
    -(6 as libc::c_int) as libc::c_short,
    -(49 as libc::c_int) as libc::c_short,
    -(96 as libc::c_int) as libc::c_short,
    -(19 as libc::c_int) as libc::c_short,
    17 as libc::c_int as libc::c_short,
    -(58 as libc::c_int) as libc::c_short,
    17 as libc::c_int as libc::c_short,
    -(0 as libc::c_int) as libc::c_short,
    -(13 as libc::c_int) as libc::c_short,
    -(170 as libc::c_int) as libc::c_short,
    25 as libc::c_int as libc::c_short,
    -(35 as libc::c_int) as libc::c_short,
    59 as libc::c_int as libc::c_short,
    10 as libc::c_int as libc::c_short,
    -(31 as libc::c_int) as libc::c_short,
    -(413 as libc::c_int) as libc::c_short,
    81 as libc::c_int as libc::c_short,
    62 as libc::c_int as libc::c_short,
    18 as libc::c_int as libc::c_short,
    -(164 as libc::c_int) as libc::c_short,
    245 as libc::c_int as libc::c_short,
    92 as libc::c_int as libc::c_short,
    -(165 as libc::c_int) as libc::c_short,
    42 as libc::c_int as libc::c_short,
    26 as libc::c_int as libc::c_short,
    126 as libc::c_int as libc::c_short,
    -(248 as libc::c_int) as libc::c_short,
    193 as libc::c_int as libc::c_short,
    -(55 as libc::c_int) as libc::c_short,
    16 as libc::c_int as libc::c_short,
    39 as libc::c_int as libc::c_short,
    14 as libc::c_int as libc::c_short,
    50 as libc::c_int as libc::c_short,
];
#[no_mangle]
pub static mut SKP_Silk_NLSF_CB1_16_Stage_info: [SKP_Silk_NLSF_CBS; 10] = [SKP_Silk_NLSF_CBS {
    nVectors: 0,
    CB_NLSF_Q15: 0 as *const libc::c_short,
    Rates_Q5: 0 as *const libc::c_short,
}; 10];
#[no_mangle]
pub static mut SKP_Silk_NLSF_CB1_16: SKP_Silk_NLSF_CB_struct = unsafe {
    {
        let mut init = SKP_Silk_NLSF_CB_struct {
            nStages: 10 as libc::c_int,
            CBStages: SKP_Silk_NLSF_CB1_16_Stage_info.as_ptr(),
            NDeltaMin_Q15: SKP_Silk_NLSF_MSVQ_CB1_16_ndelta_min_Q15.as_ptr(),
            CDF: SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr(),
            StartPtr: SKP_Silk_NLSF_MSVQ_CB1_16_CDF_start_ptr.as_ptr(),
            MiddleIx: SKP_Silk_NLSF_MSVQ_CB1_16_CDF_middle_idx.as_ptr(),
        };
        init
    }
};
unsafe extern "C" fn run_static_initializers() {
    SKP_Silk_NLSF_MSVQ_CB1_16_CDF_start_ptr = [
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(0 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(33 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(42 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(51 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(60 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(69 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(78 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(87 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(96 as libc::c_int as isize)
            as *const libc::c_ushort,
        &*SKP_Silk_NLSF_MSVQ_CB1_16_CDF.as_ptr().offset(105 as libc::c_int as isize)
            as *const libc::c_ushort,
    ];
    SKP_Silk_NLSF_CB1_16_Stage_info = [
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 32 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 0 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(0 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 32 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(32 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 40 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(40 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 48 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(48 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 56 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(56 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 64 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(64 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 72 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(72 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 80 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(80 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 88 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(88 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
        {
            let mut init = SKP_Silk_NLSF_CBS {
                nVectors: 8 as libc::c_int,
                CB_NLSF_Q15: &*SKP_Silk_NLSF_MSVQ_CB1_16_Q15
                    .as_ptr()
                    .offset((16 as libc::c_int * 96 as libc::c_int) as isize)
                    as *const libc::c_short,
                Rates_Q5: &*SKP_Silk_NLSF_MSVQ_CB1_16_rates_Q5
                    .as_ptr()
                    .offset(96 as libc::c_int as isize) as *const libc::c_short,
            };
            init
        },
    ];
    sleep(Duration::from_nanos(1));
}
#[used]
#[cfg_attr(target_os = "linux", link_section = ".init_array")]
#[cfg_attr(target_os = "windows", link_section = ".CRT$XIB")]
#[cfg_attr(target_os = "macos", link_section = "__DATA,__mod_init_func")]
static INIT_ARRAY: [unsafe extern "C" fn(); 1] = [run_static_initializers];
