#![allow(dead_code, mutable_transmutes, non_camel_case_types, non_snake_case, non_upper_case_globals, unused_assignments, unused_mut)]
pub static SKP_Silk_CB_lags_stage2: [[libc::c_short; 11]; 4] = [
    [
        0 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
    ],
    [
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
    ],
    [
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
    ],
    [
        0 as libc::c_int as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        2 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
    ],
];
pub static SKP_Silk_CB_lags_stage3: [[libc::c_short; 34]; 4] = [
    [
        -(9 as libc::c_int) as libc::c_short,
        -(7 as libc::c_int) as libc::c_short,
        -(6 as libc::c_int) as libc::c_short,
        -(5 as libc::c_int) as libc::c_short,
        -(5 as libc::c_int) as libc::c_short,
        -(4 as libc::c_int) as libc::c_short,
        -(4 as libc::c_int) as libc::c_short,
        -(3 as libc::c_int) as libc::c_short,
        -(3 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        3 as libc::c_int as libc::c_short,
        3 as libc::c_int as libc::c_short,
        4 as libc::c_int as libc::c_short,
        4 as libc::c_int as libc::c_short,
        5 as libc::c_int as libc::c_short,
        6 as libc::c_int as libc::c_short,
        5 as libc::c_int as libc::c_short,
        6 as libc::c_int as libc::c_short,
        8 as libc::c_int as libc::c_short,
    ],
    [
        -(3 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        3 as libc::c_int as libc::c_short,
    ],
    [
        3 as libc::c_int as libc::c_short,
        3 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
    ],
    [
        9 as libc::c_int as libc::c_short,
        8 as libc::c_int as libc::c_short,
        6 as libc::c_int as libc::c_short,
        5 as libc::c_int as libc::c_short,
        6 as libc::c_int as libc::c_short,
        5 as libc::c_int as libc::c_short,
        4 as libc::c_int as libc::c_short,
        4 as libc::c_int as libc::c_short,
        3 as libc::c_int as libc::c_short,
        3 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        2 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        1 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        0 as libc::c_int as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(2 as libc::c_int) as libc::c_short,
        -(3 as libc::c_int) as libc::c_short,
        -(3 as libc::c_int) as libc::c_short,
        -(4 as libc::c_int) as libc::c_short,
        -(4 as libc::c_int) as libc::c_short,
        -(5 as libc::c_int) as libc::c_short,
        -(5 as libc::c_int) as libc::c_short,
        -(6 as libc::c_int) as libc::c_short,
        -(7 as libc::c_int) as libc::c_short,
    ],
];
pub static SKP_Silk_Lag_range_stage3: [[[libc::c_short; 2]; 4]; 3] = [
    [
        [-(2 as libc::c_int) as libc::c_short, 6 as libc::c_int as libc::c_short],
        [-(1 as libc::c_int) as libc::c_short, 5 as libc::c_int as libc::c_short],
        [-(1 as libc::c_int) as libc::c_short, 5 as libc::c_int as libc::c_short],
        [-(2 as libc::c_int) as libc::c_short, 7 as libc::c_int as libc::c_short],
    ],
    [
        [-(4 as libc::c_int) as libc::c_short, 8 as libc::c_int as libc::c_short],
        [-(1 as libc::c_int) as libc::c_short, 6 as libc::c_int as libc::c_short],
        [-(1 as libc::c_int) as libc::c_short, 6 as libc::c_int as libc::c_short],
        [-(4 as libc::c_int) as libc::c_short, 9 as libc::c_int as libc::c_short],
    ],
    [
        [-(9 as libc::c_int) as libc::c_short, 12 as libc::c_int as libc::c_short],
        [-(3 as libc::c_int) as libc::c_short, 7 as libc::c_int as libc::c_short],
        [-(2 as libc::c_int) as libc::c_short, 7 as libc::c_int as libc::c_short],
        [-(7 as libc::c_int) as libc::c_short, 13 as libc::c_int as libc::c_short],
    ],
];
pub static SKP_Silk_cbk_sizes_stage3: [libc::c_short; 3] = [
    16 as libc::c_int as libc::c_short,
    24 as libc::c_int as libc::c_short,
    34 as libc::c_int as libc::c_short,
];
pub static SKP_Silk_cbk_offsets_stage3: [libc::c_short; 3] = [
    (34 as libc::c_int - 16 as libc::c_int >> 1 as libc::c_int) as libc::c_short,
    (34 as libc::c_int - 24 as libc::c_int >> 1 as libc::c_int) as libc::c_short,
    0 as libc::c_int as libc::c_short,
];
