#![allow(dead_code, mutable_transmutes, non_camel_case_types, non_snake_case, non_upper_case_globals, unused_assignments, unused_mut)]

use std::{time::Duration, thread::sleep};
#[no_mangle]
pub static mut SKP_Silk_LTP_per_index_CDF: [libc::c_ushort; 4] = [
    0 as libc::c_int as libc::c_ushort,
    20992 as libc::c_int as libc::c_ushort,
    40788 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
];
#[no_mangle]
pub static mut SKP_Silk_LTP_per_index_CDF_offset: libc::c_int = 1 as libc::c_int;
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_CDF_0: [libc::c_ushort; 11] = [
    0 as libc::c_int as libc::c_ushort,
    49380 as libc::c_int as libc::c_ushort,
    54463 as libc::c_int as libc::c_ushort,
    56494 as libc::c_int as libc::c_ushort,
    58437 as libc::c_int as libc::c_ushort,
    60101 as libc::c_int as libc::c_ushort,
    61683 as libc::c_int as libc::c_ushort,
    62985 as libc::c_int as libc::c_ushort,
    64066 as libc::c_int as libc::c_ushort,
    64823 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_CDF_1: [libc::c_ushort; 21] = [
    0 as libc::c_int as libc::c_ushort,
    25290 as libc::c_int as libc::c_ushort,
    30654 as libc::c_int as libc::c_ushort,
    35710 as libc::c_int as libc::c_ushort,
    40386 as libc::c_int as libc::c_ushort,
    42937 as libc::c_int as libc::c_ushort,
    45250 as libc::c_int as libc::c_ushort,
    47459 as libc::c_int as libc::c_ushort,
    49411 as libc::c_int as libc::c_ushort,
    51348 as libc::c_int as libc::c_ushort,
    52974 as libc::c_int as libc::c_ushort,
    54517 as libc::c_int as libc::c_ushort,
    55976 as libc::c_int as libc::c_ushort,
    57423 as libc::c_int as libc::c_ushort,
    58865 as libc::c_int as libc::c_ushort,
    60285 as libc::c_int as libc::c_ushort,
    61667 as libc::c_int as libc::c_ushort,
    62895 as libc::c_int as libc::c_ushort,
    63827 as libc::c_int as libc::c_ushort,
    64724 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_CDF_2: [libc::c_ushort; 41] = [
    0 as libc::c_int as libc::c_ushort,
    4958 as libc::c_int as libc::c_ushort,
    9439 as libc::c_int as libc::c_ushort,
    13581 as libc::c_int as libc::c_ushort,
    17638 as libc::c_int as libc::c_ushort,
    21651 as libc::c_int as libc::c_ushort,
    25015 as libc::c_int as libc::c_ushort,
    28025 as libc::c_int as libc::c_ushort,
    30287 as libc::c_int as libc::c_ushort,
    32406 as libc::c_int as libc::c_ushort,
    34330 as libc::c_int as libc::c_ushort,
    36240 as libc::c_int as libc::c_ushort,
    38130 as libc::c_int as libc::c_ushort,
    39790 as libc::c_int as libc::c_ushort,
    41281 as libc::c_int as libc::c_ushort,
    42764 as libc::c_int as libc::c_ushort,
    44229 as libc::c_int as libc::c_ushort,
    45676 as libc::c_int as libc::c_ushort,
    47081 as libc::c_int as libc::c_ushort,
    48431 as libc::c_int as libc::c_ushort,
    49675 as libc::c_int as libc::c_ushort,
    50849 as libc::c_int as libc::c_ushort,
    51932 as libc::c_int as libc::c_ushort,
    52966 as libc::c_int as libc::c_ushort,
    53957 as libc::c_int as libc::c_ushort,
    54936 as libc::c_int as libc::c_ushort,
    55869 as libc::c_int as libc::c_ushort,
    56789 as libc::c_int as libc::c_ushort,
    57708 as libc::c_int as libc::c_ushort,
    58504 as libc::c_int as libc::c_ushort,
    59285 as libc::c_int as libc::c_ushort,
    60043 as libc::c_int as libc::c_ushort,
    60796 as libc::c_int as libc::c_ushort,
    61542 as libc::c_int as libc::c_ushort,
    62218 as libc::c_int as libc::c_ushort,
    62871 as libc::c_int as libc::c_ushort,
    63483 as libc::c_int as libc::c_ushort,
    64076 as libc::c_int as libc::c_ushort,
    64583 as libc::c_int as libc::c_ushort,
    65062 as libc::c_int as libc::c_ushort,
    65535 as libc::c_int as libc::c_ushort,
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_CDF_offsets: [libc::c_int; 3] = [
    1 as libc::c_int,
    3 as libc::c_int,
    10 as libc::c_int,
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_middle_avg_RD_Q14: libc::c_int = 11010 as libc::c_int;
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_BITS_Q6_0: [libc::c_short; 10] = [
    26 as libc::c_int as libc::c_short,
    236 as libc::c_int as libc::c_short,
    321 as libc::c_int as libc::c_short,
    325 as libc::c_int as libc::c_short,
    339 as libc::c_int as libc::c_short,
    344 as libc::c_int as libc::c_short,
    362 as libc::c_int as libc::c_short,
    379 as libc::c_int as libc::c_short,
    412 as libc::c_int as libc::c_short,
    418 as libc::c_int as libc::c_short,
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_BITS_Q6_1: [libc::c_short; 20] = [
    88 as libc::c_int as libc::c_short,
    231 as libc::c_int as libc::c_short,
    237 as libc::c_int as libc::c_short,
    244 as libc::c_int as libc::c_short,
    300 as libc::c_int as libc::c_short,
    309 as libc::c_int as libc::c_short,
    313 as libc::c_int as libc::c_short,
    324 as libc::c_int as libc::c_short,
    325 as libc::c_int as libc::c_short,
    341 as libc::c_int as libc::c_short,
    346 as libc::c_int as libc::c_short,
    351 as libc::c_int as libc::c_short,
    352 as libc::c_int as libc::c_short,
    352 as libc::c_int as libc::c_short,
    354 as libc::c_int as libc::c_short,
    356 as libc::c_int as libc::c_short,
    367 as libc::c_int as libc::c_short,
    393 as libc::c_int as libc::c_short,
    396 as libc::c_int as libc::c_short,
    406 as libc::c_int as libc::c_short,
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_BITS_Q6_2: [libc::c_short; 40] = [
    238 as libc::c_int as libc::c_short,
    248 as libc::c_int as libc::c_short,
    255 as libc::c_int as libc::c_short,
    257 as libc::c_int as libc::c_short,
    258 as libc::c_int as libc::c_short,
    274 as libc::c_int as libc::c_short,
    284 as libc::c_int as libc::c_short,
    311 as libc::c_int as libc::c_short,
    317 as libc::c_int as libc::c_short,
    326 as libc::c_int as libc::c_short,
    326 as libc::c_int as libc::c_short,
    327 as libc::c_int as libc::c_short,
    339 as libc::c_int as libc::c_short,
    349 as libc::c_int as libc::c_short,
    350 as libc::c_int as libc::c_short,
    351 as libc::c_int as libc::c_short,
    352 as libc::c_int as libc::c_short,
    355 as libc::c_int as libc::c_short,
    358 as libc::c_int as libc::c_short,
    366 as libc::c_int as libc::c_short,
    371 as libc::c_int as libc::c_short,
    379 as libc::c_int as libc::c_short,
    383 as libc::c_int as libc::c_short,
    387 as libc::c_int as libc::c_short,
    388 as libc::c_int as libc::c_short,
    393 as libc::c_int as libc::c_short,
    394 as libc::c_int as libc::c_short,
    394 as libc::c_int as libc::c_short,
    407 as libc::c_int as libc::c_short,
    409 as libc::c_int as libc::c_short,
    412 as libc::c_int as libc::c_short,
    412 as libc::c_int as libc::c_short,
    413 as libc::c_int as libc::c_short,
    422 as libc::c_int as libc::c_short,
    426 as libc::c_int as libc::c_short,
    432 as libc::c_int as libc::c_short,
    434 as libc::c_int as libc::c_short,
    449 as libc::c_int as libc::c_short,
    454 as libc::c_int as libc::c_short,
    455 as libc::c_int as libc::c_short,
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_CDF_ptrs: [&'static [u16]; 3] = unsafe {
    [
        &SKP_Silk_LTP_gain_CDF_0,
        &SKP_Silk_LTP_gain_CDF_1,
        &SKP_Silk_LTP_gain_CDF_2,
    ]
};
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_BITS_Q6_ptrs: [*const libc::c_short; 3] = unsafe {
    [
        SKP_Silk_LTP_gain_BITS_Q6_0.as_ptr(),
        SKP_Silk_LTP_gain_BITS_Q6_1.as_ptr(),
        SKP_Silk_LTP_gain_BITS_Q6_2.as_ptr(),
    ]
};
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_vq_0_Q14: [[libc::c_short; 5]; 10] = [
    [
        594 as libc::c_int as libc::c_short,
        984 as libc::c_int as libc::c_short,
        2840 as libc::c_int as libc::c_short,
        1021 as libc::c_int as libc::c_short,
        669 as libc::c_int as libc::c_short,
    ],
    [
        10 as libc::c_int as libc::c_short,
        35 as libc::c_int as libc::c_short,
        304 as libc::c_int as libc::c_short,
        -(1 as libc::c_int) as libc::c_short,
        23 as libc::c_int as libc::c_short,
    ],
    [
        -(694 as libc::c_int) as libc::c_short,
        1923 as libc::c_int as libc::c_short,
        4603 as libc::c_int as libc::c_short,
        2975 as libc::c_int as libc::c_short,
        2335 as libc::c_int as libc::c_short,
    ],
    [
        2437 as libc::c_int as libc::c_short,
        3176 as libc::c_int as libc::c_short,
        3778 as libc::c_int as libc::c_short,
        1940 as libc::c_int as libc::c_short,
        481 as libc::c_int as libc::c_short,
    ],
    [
        214 as libc::c_int as libc::c_short,
        -(46 as libc::c_int) as libc::c_short,
        7870 as libc::c_int as libc::c_short,
        4406 as libc::c_int as libc::c_short,
        -(521 as libc::c_int) as libc::c_short,
    ],
    [
        -(896 as libc::c_int) as libc::c_short,
        4818 as libc::c_int as libc::c_short,
        8501 as libc::c_int as libc::c_short,
        1623 as libc::c_int as libc::c_short,
        -(887 as libc::c_int) as libc::c_short,
    ],
    [
        -(696 as libc::c_int) as libc::c_short,
        3178 as libc::c_int as libc::c_short,
        6480 as libc::c_int as libc::c_short,
        -(302 as libc::c_int) as libc::c_short,
        1081 as libc::c_int as libc::c_short,
    ],
    [
        517 as libc::c_int as libc::c_short,
        599 as libc::c_int as libc::c_short,
        1002 as libc::c_int as libc::c_short,
        567 as libc::c_int as libc::c_short,
        560 as libc::c_int as libc::c_short,
    ],
    [
        -(2075 as libc::c_int) as libc::c_short,
        -(834 as libc::c_int) as libc::c_short,
        4712 as libc::c_int as libc::c_short,
        -(340 as libc::c_int) as libc::c_short,
        896 as libc::c_int as libc::c_short,
    ],
    [
        1435 as libc::c_int as libc::c_short,
        -(644 as libc::c_int) as libc::c_short,
        3993 as libc::c_int as libc::c_short,
        -(612 as libc::c_int) as libc::c_short,
        -(2063 as libc::c_int) as libc::c_short,
    ],
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_vq_1_Q14: [[libc::c_short; 5]; 20] = [
    [
        1655 as libc::c_int as libc::c_short,
        2918 as libc::c_int as libc::c_short,
        5001 as libc::c_int as libc::c_short,
        3010 as libc::c_int as libc::c_short,
        1775 as libc::c_int as libc::c_short,
    ],
    [
        113 as libc::c_int as libc::c_short,
        198 as libc::c_int as libc::c_short,
        856 as libc::c_int as libc::c_short,
        176 as libc::c_int as libc::c_short,
        178 as libc::c_int as libc::c_short,
    ],
    [
        -(843 as libc::c_int) as libc::c_short,
        2479 as libc::c_int as libc::c_short,
        7858 as libc::c_int as libc::c_short,
        5371 as libc::c_int as libc::c_short,
        574 as libc::c_int as libc::c_short,
    ],
    [
        59 as libc::c_int as libc::c_short,
        5356 as libc::c_int as libc::c_short,
        7648 as libc::c_int as libc::c_short,
        2850 as libc::c_int as libc::c_short,
        -(315 as libc::c_int) as libc::c_short,
    ],
    [
        3840 as libc::c_int as libc::c_short,
        4851 as libc::c_int as libc::c_short,
        6527 as libc::c_int as libc::c_short,
        1583 as libc::c_int as libc::c_short,
        -(1233 as libc::c_int) as libc::c_short,
    ],
    [
        1620 as libc::c_int as libc::c_short,
        1760 as libc::c_int as libc::c_short,
        2330 as libc::c_int as libc::c_short,
        1876 as libc::c_int as libc::c_short,
        2045 as libc::c_int as libc::c_short,
    ],
    [
        -(545 as libc::c_int) as libc::c_short,
        1854 as libc::c_int as libc::c_short,
        11792 as libc::c_int as libc::c_short,
        1547 as libc::c_int as libc::c_short,
        -(307 as libc::c_int) as libc::c_short,
    ],
    [
        -(604 as libc::c_int) as libc::c_short,
        689 as libc::c_int as libc::c_short,
        5369 as libc::c_int as libc::c_short,
        5074 as libc::c_int as libc::c_short,
        4265 as libc::c_int as libc::c_short,
    ],
    [
        521 as libc::c_int as libc::c_short,
        -(1331 as libc::c_int) as libc::c_short,
        9829 as libc::c_int as libc::c_short,
        6209 as libc::c_int as libc::c_short,
        -(1211 as libc::c_int) as libc::c_short,
    ],
    [
        -(1315 as libc::c_int) as libc::c_short,
        6747 as libc::c_int as libc::c_short,
        9929 as libc::c_int as libc::c_short,
        -(1410 as libc::c_int) as libc::c_short,
        546 as libc::c_int as libc::c_short,
    ],
    [
        117 as libc::c_int as libc::c_short,
        -(144 as libc::c_int) as libc::c_short,
        2810 as libc::c_int as libc::c_short,
        1649 as libc::c_int as libc::c_short,
        5240 as libc::c_int as libc::c_short,
    ],
    [
        5392 as libc::c_int as libc::c_short,
        3476 as libc::c_int as libc::c_short,
        2425 as libc::c_int as libc::c_short,
        -(38 as libc::c_int) as libc::c_short,
        633 as libc::c_int as libc::c_short,
    ],
    [
        14 as libc::c_int as libc::c_short,
        -(449 as libc::c_int) as libc::c_short,
        5274 as libc::c_int as libc::c_short,
        3547 as libc::c_int as libc::c_short,
        -(171 as libc::c_int) as libc::c_short,
    ],
    [
        -(98 as libc::c_int) as libc::c_short,
        395 as libc::c_int as libc::c_short,
        9114 as libc::c_int as libc::c_short,
        1676 as libc::c_int as libc::c_short,
        844 as libc::c_int as libc::c_short,
    ],
    [
        -(908 as libc::c_int) as libc::c_short,
        3843 as libc::c_int as libc::c_short,
        8861 as libc::c_int as libc::c_short,
        -(957 as libc::c_int) as libc::c_short,
        1474 as libc::c_int as libc::c_short,
    ],
    [
        396 as libc::c_int as libc::c_short,
        6747 as libc::c_int as libc::c_short,
        5379 as libc::c_int as libc::c_short,
        -(329 as libc::c_int) as libc::c_short,
        1269 as libc::c_int as libc::c_short,
    ],
    [
        -(335 as libc::c_int) as libc::c_short,
        2830 as libc::c_int as libc::c_short,
        4281 as libc::c_int as libc::c_short,
        270 as libc::c_int as libc::c_short,
        -(54 as libc::c_int) as libc::c_short,
    ],
    [
        1502 as libc::c_int as libc::c_short,
        5609 as libc::c_int as libc::c_short,
        8958 as libc::c_int as libc::c_short,
        6045 as libc::c_int as libc::c_short,
        2059 as libc::c_int as libc::c_short,
    ],
    [
        -(370 as libc::c_int) as libc::c_short,
        479 as libc::c_int as libc::c_short,
        5267 as libc::c_int as libc::c_short,
        5726 as libc::c_int as libc::c_short,
        1174 as libc::c_int as libc::c_short,
    ],
    [
        5237 as libc::c_int as libc::c_short,
        -(1144 as libc::c_int) as libc::c_short,
        6510 as libc::c_int as libc::c_short,
        455 as libc::c_int as libc::c_short,
        512 as libc::c_int as libc::c_short,
    ],
];
#[no_mangle]
pub static mut SKP_Silk_LTP_gain_vq_2_Q14: [[libc::c_short; 5]; 40] = [
    [
        -(278 as libc::c_int) as libc::c_short,
        415 as libc::c_int as libc::c_short,
        9345 as libc::c_int as libc::c_short,
        7106 as libc::c_int as libc::c_short,
        -(431 as libc::c_int) as libc::c_short,
    ],
    [
        -(1006 as libc::c_int) as libc::c_short,
        3863 as libc::c_int as libc::c_short,
        9524 as libc::c_int as libc::c_short,
        4724 as libc::c_int as libc::c_short,
        -(871 as libc::c_int) as libc::c_short,
    ],
    [
        -(954 as libc::c_int) as libc::c_short,
        4624 as libc::c_int as libc::c_short,
        11722 as libc::c_int as libc::c_short,
        973 as libc::c_int as libc::c_short,
        -(300 as libc::c_int) as libc::c_short,
    ],
    [
        -(117 as libc::c_int) as libc::c_short,
        7066 as libc::c_int as libc::c_short,
        8331 as libc::c_int as libc::c_short,
        1959 as libc::c_int as libc::c_short,
        -(901 as libc::c_int) as libc::c_short,
    ],
    [
        593 as libc::c_int as libc::c_short,
        3412 as libc::c_int as libc::c_short,
        6070 as libc::c_int as libc::c_short,
        4914 as libc::c_int as libc::c_short,
        1567 as libc::c_int as libc::c_short,
    ],
    [
        54 as libc::c_int as libc::c_short,
        -(51 as libc::c_int) as libc::c_short,
        12618 as libc::c_int as libc::c_short,
        4228 as libc::c_int as libc::c_short,
        -(844 as libc::c_int) as libc::c_short,
    ],
    [
        3157 as libc::c_int as libc::c_short,
        4822 as libc::c_int as libc::c_short,
        5229 as libc::c_int as libc::c_short,
        2313 as libc::c_int as libc::c_short,
        717 as libc::c_int as libc::c_short,
    ],
    [
        -(244 as libc::c_int) as libc::c_short,
        1161 as libc::c_int as libc::c_short,
        14198 as libc::c_int as libc::c_short,
        779 as libc::c_int as libc::c_short,
        69 as libc::c_int as libc::c_short,
    ],
    [
        -(1218 as libc::c_int) as libc::c_short,
        5603 as libc::c_int as libc::c_short,
        12894 as libc::c_int as libc::c_short,
        -(2301 as libc::c_int) as libc::c_short,
        1001 as libc::c_int as libc::c_short,
    ],
    [
        -(132 as libc::c_int) as libc::c_short,
        3960 as libc::c_int as libc::c_short,
        9526 as libc::c_int as libc::c_short,
        577 as libc::c_int as libc::c_short,
        1806 as libc::c_int as libc::c_short,
    ],
    [
        -(1633 as libc::c_int) as libc::c_short,
        8815 as libc::c_int as libc::c_short,
        10484 as libc::c_int as libc::c_short,
        -(2452 as libc::c_int) as libc::c_short,
        895 as libc::c_int as libc::c_short,
    ],
    [
        235 as libc::c_int as libc::c_short,
        450 as libc::c_int as libc::c_short,
        1243 as libc::c_int as libc::c_short,
        667 as libc::c_int as libc::c_short,
        437 as libc::c_int as libc::c_short,
    ],
    [
        959 as libc::c_int as libc::c_short,
        -(2630 as libc::c_int) as libc::c_short,
        10897 as libc::c_int as libc::c_short,
        8772 as libc::c_int as libc::c_short,
        -(1852 as libc::c_int) as libc::c_short,
    ],
    [
        2420 as libc::c_int as libc::c_short,
        2046 as libc::c_int as libc::c_short,
        8893 as libc::c_int as libc::c_short,
        4427 as libc::c_int as libc::c_short,
        -(1569 as libc::c_int) as libc::c_short,
    ],
    [
        23 as libc::c_int as libc::c_short,
        7091 as libc::c_int as libc::c_short,
        8356 as libc::c_int as libc::c_short,
        -(1285 as libc::c_int) as libc::c_short,
        1508 as libc::c_int as libc::c_short,
    ],
    [
        -(1133 as libc::c_int) as libc::c_short,
        835 as libc::c_int as libc::c_short,
        7662 as libc::c_int as libc::c_short,
        6043 as libc::c_int as libc::c_short,
        2800 as libc::c_int as libc::c_short,
    ],
    [
        439 as libc::c_int as libc::c_short,
        391 as libc::c_int as libc::c_short,
        11016 as libc::c_int as libc::c_short,
        2253 as libc::c_int as libc::c_short,
        1362 as libc::c_int as libc::c_short,
    ],
    [
        -(1020 as libc::c_int) as libc::c_short,
        2876 as libc::c_int as libc::c_short,
        13436 as libc::c_int as libc::c_short,
        4015 as libc::c_int as libc::c_short,
        -(3020 as libc::c_int) as libc::c_short,
    ],
    [
        1060 as libc::c_int as libc::c_short,
        -(2690 as libc::c_int) as libc::c_short,
        13512 as libc::c_int as libc::c_short,
        5565 as libc::c_int as libc::c_short,
        -(1394 as libc::c_int) as libc::c_short,
    ],
    [
        -(1420 as libc::c_int) as libc::c_short,
        8007 as libc::c_int as libc::c_short,
        11421 as libc::c_int as libc::c_short,
        -(152 as libc::c_int) as libc::c_short,
        -(1672 as libc::c_int) as libc::c_short,
    ],
    [
        -(893 as libc::c_int) as libc::c_short,
        2895 as libc::c_int as libc::c_short,
        15434 as libc::c_int as libc::c_short,
        -(1490 as libc::c_int) as libc::c_short,
        159 as libc::c_int as libc::c_short,
    ],
    [
        -(1054 as libc::c_int) as libc::c_short,
        428 as libc::c_int as libc::c_short,
        12208 as libc::c_int as libc::c_short,
        8538 as libc::c_int as libc::c_short,
        -(3344 as libc::c_int) as libc::c_short,
    ],
    [
        1772 as libc::c_int as libc::c_short,
        -(1304 as libc::c_int) as libc::c_short,
        7593 as libc::c_int as libc::c_short,
        6185 as libc::c_int as libc::c_short,
        561 as libc::c_int as libc::c_short,
    ],
    [
        525 as libc::c_int as libc::c_short,
        -(1207 as libc::c_int) as libc::c_short,
        6659 as libc::c_int as libc::c_short,
        11151 as libc::c_int as libc::c_short,
        -(1170 as libc::c_int) as libc::c_short,
    ],
    [
        439 as libc::c_int as libc::c_short,
        2667 as libc::c_int as libc::c_short,
        4743 as libc::c_int as libc::c_short,
        2359 as libc::c_int as libc::c_short,
        5515 as libc::c_int as libc::c_short,
    ],
    [
        2951 as libc::c_int as libc::c_short,
        7432 as libc::c_int as libc::c_short,
        7909 as libc::c_int as libc::c_short,
        -(230 as libc::c_int) as libc::c_short,
        -(1564 as libc::c_int) as libc::c_short,
    ],
    [
        -(72 as libc::c_int) as libc::c_short,
        2140 as libc::c_int as libc::c_short,
        5477 as libc::c_int as libc::c_short,
        1391 as libc::c_int as libc::c_short,
        1580 as libc::c_int as libc::c_short,
    ],
    [
        476 as libc::c_int as libc::c_short,
        -(1312 as libc::c_int) as libc::c_short,
        15912 as libc::c_int as libc::c_short,
        2174 as libc::c_int as libc::c_short,
        -(1027 as libc::c_int) as libc::c_short,
    ],
    [
        5737 as libc::c_int as libc::c_short,
        441 as libc::c_int as libc::c_short,
        2493 as libc::c_int as libc::c_short,
        2043 as libc::c_int as libc::c_short,
        2757 as libc::c_int as libc::c_short,
    ],
    [
        228 as libc::c_int as libc::c_short,
        -(43 as libc::c_int) as libc::c_short,
        1803 as libc::c_int as libc::c_short,
        6663 as libc::c_int as libc::c_short,
        7064 as libc::c_int as libc::c_short,
    ],
    [
        4596 as libc::c_int as libc::c_short,
        9182 as libc::c_int as libc::c_short,
        1917 as libc::c_int as libc::c_short,
        -(200 as libc::c_int) as libc::c_short,
        203 as libc::c_int as libc::c_short,
    ],
    [
        -(704 as libc::c_int) as libc::c_short,
        12039 as libc::c_int as libc::c_short,
        5451 as libc::c_int as libc::c_short,
        -(1188 as libc::c_int) as libc::c_short,
        542 as libc::c_int as libc::c_short,
    ],
    [
        1782 as libc::c_int as libc::c_short,
        -(1040 as libc::c_int) as libc::c_short,
        10078 as libc::c_int as libc::c_short,
        7513 as libc::c_int as libc::c_short,
        -(2767 as libc::c_int) as libc::c_short,
    ],
    [
        -(2626 as libc::c_int) as libc::c_short,
        7747 as libc::c_int as libc::c_short,
        9019 as libc::c_int as libc::c_short,
        62 as libc::c_int as libc::c_short,
        1710 as libc::c_int as libc::c_short,
    ],
    [
        235 as libc::c_int as libc::c_short,
        -(233 as libc::c_int) as libc::c_short,
        2954 as libc::c_int as libc::c_short,
        10921 as libc::c_int as libc::c_short,
        1947 as libc::c_int as libc::c_short,
    ],
    [
        10854 as libc::c_int as libc::c_short,
        2814 as libc::c_int as libc::c_short,
        1232 as libc::c_int as libc::c_short,
        -(111 as libc::c_int) as libc::c_short,
        222 as libc::c_int as libc::c_short,
    ],
    [
        2267 as libc::c_int as libc::c_short,
        2778 as libc::c_int as libc::c_short,
        12325 as libc::c_int as libc::c_short,
        156 as libc::c_int as libc::c_short,
        -(1658 as libc::c_int) as libc::c_short,
    ],
    [
        -(2950 as libc::c_int) as libc::c_short,
        8095 as libc::c_int as libc::c_short,
        16330 as libc::c_int as libc::c_short,
        268 as libc::c_int as libc::c_short,
        -(3626 as libc::c_int) as libc::c_short,
    ],
    [
        67 as libc::c_int as libc::c_short,
        2083 as libc::c_int as libc::c_short,
        7950 as libc::c_int as libc::c_short,
        -(80 as libc::c_int) as libc::c_short,
        -(2432 as libc::c_int) as libc::c_short,
    ],
    [
        518 as libc::c_int as libc::c_short,
        -(66 as libc::c_int) as libc::c_short,
        1718 as libc::c_int as libc::c_short,
        415 as libc::c_int as libc::c_short,
        11435 as libc::c_int as libc::c_short,
    ],
];
#[no_mangle]
pub static mut SKP_Silk_LTP_vq_ptrs_Q14: [*const libc::c_short; 3] = [0
    as *const libc::c_short; 3];
#[no_mangle]
pub static mut SKP_Silk_LTP_vq_sizes: [libc::c_int; 3] = [
    10 as libc::c_int,
    20 as libc::c_int,
    40 as libc::c_int,
];
unsafe extern "C" fn run_static_initializers() {
    SKP_Silk_LTP_vq_ptrs_Q14 = [
        &*(*SKP_Silk_LTP_gain_vq_0_Q14.as_ptr().offset(0 as libc::c_int as isize))
            .as_ptr()
            .offset(0 as libc::c_int as isize) as *const libc::c_short,
        &*(*SKP_Silk_LTP_gain_vq_1_Q14.as_ptr().offset(0 as libc::c_int as isize))
            .as_ptr()
            .offset(0 as libc::c_int as isize) as *const libc::c_short,
        &*(*SKP_Silk_LTP_gain_vq_2_Q14.as_ptr().offset(0 as libc::c_int as isize))
            .as_ptr()
            .offset(0 as libc::c_int as isize) as *const libc::c_short,
    ];
    sleep(Duration::from_nanos(1));
}
#[used]
#[cfg_attr(target_os = "linux", link_section = ".init_array")]
#[cfg_attr(target_os = "windows", link_section = ".CRT$XIB")]
#[cfg_attr(target_os = "macos", link_section = "__DATA,__mod_init_func")]
static INIT_ARRAY: [unsafe extern "C" fn(); 1] = [run_static_initializers];
